import { z } from "zod";

export const currencyName = z.enum([
  "Abkhazian apsar",
  "Afghan afghani",
  "Euro",
  "Albanian lek",
  "Algerian dinar",
  "Angolan kwanza",
  "Eastern Caribbean dollar",
  "Argentine peso",
  "Armenian dram",
  "Aruban florin",
  "Ascension Island Saint Helena pound",
  "Australian dollar",
  "Azerbaijani manat",
  "Bahamian dollar",
  "Bahraini dinar",
  "Bangladeshi taka",
  "Barbadian dollar",
  "Belarusian ruble",
  "Belize dollar",
  "West African CFA franc",
  "Bermudian dollar",
  "Bhutanese ngultrum",
  "Indian rupee",
  "Bolivian boliviano",
  "United States dollar",
  "Bosnia and Herzegovina convertible mark",
  "Botswana pula",
  "Brazilian real",
  "Brunei dollar",
  "Singapore dollar",
  "Bulgarian lev",
  "Burundian franc",
  "Cambodian riel",
  "Central African CFA franc",
  "Canadian dollar",
  "Cape Verdean escudo",
  "Cayman Islands dollar",
  "Chilean peso",
  "Renminbi",
  "Colombian peso",
  "Comorian franc",
  "Congolese franc",
  "Cook Islands dollar",
  "New Zealand dollar",
  "Costa Rican colón",
  "Cuban peso",
  "Caribbean guilder",
  "Czech koruna",
  "Danish krone",
  "Djiboutian franc",
  "Dominican peso",
  "Egyptian pound",
  "Eritrean nakfa",
  "Swazi lilangeni",
  "South African rand",
  "Ethiopian birr",
  "Falkland Islands pound",
  "Sterling",
  "Faroese króna",
  "Fijian dollar",
  "CFP franc",
  "Gambian dalasi",
  "Georgian lari",
  "Ghanaian cedi",
  "Gibraltar pound",
  "Guatemalan quetzal",
  "Guernsey pound",
  "Guinean franc",
  "Guyanese dollar",
  "Haitian gourde",
  "Honduran lempira",
  "Hong Kong dollar",
  "Hungarian forint",
  "Icelandic króna",
  "Indonesian rupiah",
  "Iranian rial",
  "Iraqi dinar",
  "Manx pound",
  "Israeli new shekel",
  "Jamaican dollar",
  "Japanese yen",
  "Jersey pound",
  "Jordanian dinar",
  "Kazakhstani tenge",
  "Kenyan shilling",
  "Kiribati dollar",
  "North Korean won",
  "South Korean won",
  "Kuwaiti dinar",
  "Kyrgyz som",
  "Lao kip",
  "Lebanese pound",
  "Lesotho loti",
  "Liberian dollar",
  "Libyan dinar",
  "Swiss franc",
  "Macanese pataca",
  "Malagasy ariary",
  "Malawian kwacha",
  "Malaysian ringgit",
  "Maldivian rufiyaa",
  "Mauritanian ouguiya",
  "Mauritian rupee",
  "Mexican peso",
  "Moldovan leu",
  "Mongolian tögrög",
  "Moroccan dirham",
  "Mozambican metical",
  "Burmese kyat",
  "Namibian dollar",
  "Nepalese rupee",
  "Nicaraguan córdoba",
  "Nigerian naira",
  "Niue dollar",
  "Macedonian denar",
  "Turkish lira",
  "Norwegian krone",
  "Omani rial",
  "Pakistani rupee",
  "Panamanian balboa",
  "Papua New Guinean kina",
  "Paraguayan guaraní",
  "Peruvian sol",
  "Philippine peso",
  "Pitcairn Islands dollar",
  "Polish złoty",
  "Qatari riyal",
  "Romanian leu",
  "Russian ruble",
  "Rwandan franc",
  "Sahrawi peseta",
  "Saint Helena pound",
  "Samoan tālā",
  "São Tomé and Príncipe dobra",
  "Saudi riyal",
  "Serbian dinar",
  "Seychellois rupee",
  "Sierra Leonean leone",
  "Solomon Islands dollar",
  "Somali shilling",
  "Somaliland shilling",
  "South Sudanese pound",
  "Sri Lankan rupee",
  "Sudanese pound",
  "Surinamese dollar",
  "Swedish krona",
  "Syrian pound",
  "New Taiwan dollar",
  "Tajikistani somoni",
  "Tanzanian shilling",
  "Thai baht",
  "Tongan paʻanga",
  "Transnistrian ruble",
  "Trinidad and Tobago dollar",
  "Tunisian dinar",
  "Turkmenistani manat",
  "Tuvaluan dollar",
  "Ugandan shilling",
  "Ukrainian hryvnia",
  "United Arab Emirates dirham",
  "Uruguayan peso",
  "Uzbekistani sum",
  "Vanuatu vatu",
  "Venezuelan sovereign bolívar",
  "Venezuelan digital bolívar",
  "Vietnamese đồng",
  "Yemeni rial",
  "Zambian kwacha",
  "Zimbabwe gold",
]);

export type CurrencyName = z.infer<typeof currencyName>;

export const isValidCurrencyName = (_currencyName: unknown) =>
  currencyName.safeParse(_currencyName).success;
