import type { Currency } from "./types";

export const currencies: Array<Currency> = [
  {
    name: "Abkhazian apsar",
    symbol: "аҧ",
  },
  {
    name: "Afghan afghani",
    symbol: "؋",
    iso4217: "AFN",
    factionalUnit: "Pul",
  },
  {
    name: "Euro",
    symbol: "€",
    iso4217: "EUR",
    factionalUnit: "Cent",
  },
  {
    name: "Albanian lek",
    symbol: "L",
    iso4217: "ALL",
    factionalUnit: "Qintar",
  },
  {
    name: "Algerian dinar",
    symbol: "DA",
    iso4217: "DZD",
    factionalUnit: "Centime",
  },
  {
    name: "Angolan kwanza",
    symbol: "Kz",
    iso4217: "AOA",
    factionalUnit: "Cêntimo",
  },
  {
    name: "Eastern Caribbean dollar",
    symbol: "EC$",
    iso4217: "XCD",
    factionalUnit: "Cent",
  },
  {
    name: "Argentine peso",
    symbol: "$",
    iso4217: "ARS",
    factionalUnit: "Centavo",
  },
  {
    name: "Armenian dram",
    symbol: "֏",
    iso4217: "AMD",
    factionalUnit: "Luma",
  },
  {
    name: "Aruban florin",
    symbol: "ƒ",
    iso4217: "AWG",
    factionalUnit: "Cent",
  },
  {
    name: "Australian dollar",
    symbol: "$",
    iso4217: "AUD",
    factionalUnit: "Cent",
  },
  {
    name: "Azerbaijani manat",
    symbol: "₼",
    iso4217: "AZN",
  },
  {
    name: "Bahamian dollar",
    symbol: "$",
    iso4217: "BSD",
    factionalUnit: "Cent",
  },
  {
    name: "Bahraini dinar",
    symbol: "BD",
    iso4217: "BHD",
    factionalUnit: "Fils",
  },
  {
    name: "Bangladeshi taka",
    symbol: "৳",
    iso4217: "BDT",
    factionalUnit: "Poisha",
  },
  {
    name: "Barbadian dollar",
    symbol: "$",
    iso4217: "BBD",
    factionalUnit: "Cent",
  },
  {
    name: "Belarusian ruble",
    symbol: "Br",
    iso4217: "BYN",
    factionalUnit: "Kopeck",
  },
  {
    name: "Belize dollar",
    symbol: "$",
    iso4217: "BZD",
    factionalUnit: "Cent",
  },
  {
    name: "West African CFA franc",
    symbol: "F.CFA",
    iso4217: "XOF",
    factionalUnit: "Centime",
  },
  {
    name: "Bermudian dollar",
    symbol: "$",
    iso4217: "BMD",
    factionalUnit: "Cent",
  },
  {
    name: "Bhutanese ngultrum",
    symbol: "Nu",
    iso4217: "BTN",
  },
  {
    name: "Indian rupee",
    symbol: "₹",
    iso4217: "INR",
    factionalUnit: "Paisa",
  },
  {
    name: "Bolivian boliviano",
    symbol: "Bs",
    iso4217: "BOB",
    factionalUnit: "Centavo",
  },
  {
    name: "United States dollar",
    symbol: "$",
    iso4217: "USD",
    factionalUnit: "Cent",
  },
  {
    name: "Bosnia and Herzegovina convertible mark",
    symbol: "KM",
    iso4217: "BAM",
    factionalUnit: "Fening",
  },
  {
    name: "Botswana pula",
    symbol: "P",
    iso4217: "BWP",
    factionalUnit: "Thebe",
  },
  {
    name: "Brazilian real",
    symbol: "R$",
    iso4217: "BRL",
    factionalUnit: "Centavo",
  },
  {
    name: "Brunei dollar",
    symbol: "$",
    iso4217: "BND",
    factionalUnit: "Sen",
  },
  {
    name: "Singapore dollar",
    symbol: "$",
    iso4217: "SGD",
    factionalUnit: "Cent",
  },
  {
    name: "Bulgarian lev",
    symbol: "lv.",
    iso4217: "BGN",
    factionalUnit: "Stotinka",
  },
  {
    name: "Burundian franc",
    symbol: "FBu",
    iso4217: "BIF",
    factionalUnit: "Centime",
  },
  {
    name: "Cambodian riel",
    symbol: "៛",
    iso4217: "KHR",
    factionalUnit: "Sen",
  },
  {
    name: "Central African CFA franc",
    symbol: "F.CFA",
    iso4217: "XAF",
    factionalUnit: "Centime",
  },
  {
    name: "Canadian dollar",
    symbol: "$",
    iso4217: "CAD",
    factionalUnit: "Cent",
  },
  {
    name: "Cape Verdean escudo",
    symbol: "CVE",
    iso4217: "CVE",
    factionalUnit: "Centavo",
  },
  {
    name: "Cayman Islands dollar",
    symbol: "$",
    iso4217: "KYD",
    factionalUnit: "Cent",
  },
  {
    name: "Chilean peso",
    symbol: "$",
    iso4217: "CLP",
    factionalUnit: "Centavo",
  },
  {
    name: "Renminbi",
    symbol: "¥",
    iso4217: "CNY",
  },
  {
    name: "Colombian peso",
    symbol: "$",
    iso4217: "COP",
    factionalUnit: "Centavo",
  },
  {
    name: "Comorian franc",
    symbol: "FC",
    iso4217: "KMF",
    factionalUnit: "Centime",
  },
  {
    name: "Congolese franc",
    symbol: "FC",
    iso4217: "CDF",
    factionalUnit: "Centime",
  },
  {
    name: "New Zealand dollar",
    symbol: "NZD",
    iso4217: "NZD",
    factionalUnit: "Cent",
  },
  {
    name: "Costa Rican colón",
    symbol: "₡",
    iso4217: "CRC",
    factionalUnit: "Céntimo",
  },
  {
    name: "Cuban peso",
    symbol: "$",
    iso4217: "CUP",
    factionalUnit: "Centavo",
  },
  {
    name: "Caribbean guilder",
    symbol: "Cg",
    iso4217: "XCG",
    factionalUnit: "Cent",
  },
  {
    name: "Czech koruna",
    symbol: "Kč",
    iso4217: "CZK",
    factionalUnit: "Heller",
  },
  {
    name: "Danish krone",
    symbol: "kr",
    iso4217: "DKK",
    factionalUnit: "Øre",
  },
  {
    name: "Djiboutian franc",
    symbol: "Fdj",
    iso4217: "DJF",
    factionalUnit: "Centime",
  },
  {
    name: "Dominican peso",
    symbol: "$",
    iso4217: "DOP",
    factionalUnit: "Centavo",
  },
  {
    name: "Egyptian pound",
    symbol: "LE",
    iso4217: "EGP",
  },
  {
    name: "Eritrean nakfa",
    symbol: "Nkf",
    iso4217: "ERN",
    factionalUnit: "Cent",
  },
  {
    name: "Swazi lilangeni",
    symbol: "L",
    iso4217: "SZL",
    factionalUnit: "Cent",
  },
  {
    name: "South African rand",
    symbol: "R",
    iso4217: "ZAR",
    factionalUnit: "Cent",
  },
  {
    name: "Ethiopian birr",
    symbol: "Br",
    iso4217: "ETB",
  },
  {
    name: "Falkland Islands pound",
    symbol: "FKP",
    iso4217: "FKP",
  },
  {
    name: "Sterling",
    symbol: "£",
    iso4217: "GBP",
  },
  {
    name: "Fijian dollar",
    symbol: "$",
    iso4217: "FJD",
    factionalUnit: "Cent",
  },
  {
    name: "CFP franc",
    symbol: "₣",
    iso4217: "XPF",
    factionalUnit: "Centime",
  },
  {
    name: "Gambian dalasi",
    symbol: "D",
    iso4217: "GMD",
    factionalUnit: "Butut",
  },
  {
    name: "Georgian lari",
    symbol: "₾",
    iso4217: "GEL",
    factionalUnit: "Tetri",
  },
  {
    name: "Ghanaian cedi",
    symbol: "₵",
    iso4217: "GHS",
    factionalUnit: "Pesewa",
  },
  {
    name: "Gibraltar pound",
    symbol: "GIP",
    iso4217: "GIP",
  },
  {
    name: "Guatemalan quetzal",
    symbol: "Q",
    iso4217: "GTQ",
    factionalUnit: "Centavo",
  },
  {
    name: "Guinean franc",
    symbol: "Fr",
    iso4217: "GNF",
    factionalUnit: "Centime",
  },
  {
    name: "Guyanese dollar",
    symbol: "$",
    iso4217: "GYD",
    factionalUnit: "Cent",
  },
  {
    name: "Haitian gourde",
    symbol: "G",
    iso4217: "HTG",
    factionalUnit: "Centime",
  },
  {
    name: "Honduran lempira",
    symbol: "L",
    iso4217: "HNL",
    factionalUnit: "Centavo",
  },
  {
    name: "Hong Kong dollar",
    symbol: "$",
    iso4217: "HKD",
    factionalUnit: "Cent",
  },
  {
    name: "Hungarian forint",
    symbol: "Ft",
    iso4217: "HUF",
  },
  {
    name: "Icelandic króna",
    symbol: "kr",
    iso4217: "ISK",
    factionalUnit: "Eyrir",
  },
  {
    name: "Indonesian rupiah",
    symbol: "Rp",
    iso4217: "IDR",
    factionalUnit: "Sen",
  },
  {
    name: "Iranian rial",
    symbol: "Rl",
    iso4217: "IRR",
    factionalUnit: "Rial",
  },
  {
    name: "Iraqi dinar",
    symbol: "ID",
    iso4217: "IQD",
    factionalUnit: "Fils",
  },
  {
    name: "Israeli new shekel",
    symbol: "₪",
    iso4217: "ILS",
    factionalUnit: "Agora",
  },
  {
    name: "Jamaican dollar",
    symbol: "$",
    iso4217: "JMD",
    factionalUnit: "Cent",
  },
  {
    name: "Japanese yen",
    symbol: "¥",
    iso4217: "JPY",
    factionalUnit: "Sen",
  },
  {
    name: "Jordanian dinar",
    symbol: "JD",
    iso4217: "JOD",
  },
  {
    name: "Kazakhstani tenge",
    symbol: "₸",
    iso4217: "KZT",
  },
  {
    name: "Kenyan shilling",
    symbol: "Sh",
    iso4217: "KES",
    factionalUnit: "Cent",
  },
  {
    name: "North Korean won",
    symbol: "₩",
    iso4217: "KPW",
  },
  {
    name: "South Korean won",
    symbol: "₩",
    iso4217: "KRW",
    factionalUnit: "Jeon",
  },
  {
    name: "Kuwaiti dinar",
    symbol: "KD",
    iso4217: "KWD",
    factionalUnit: "Fils",
  },
  {
    name: "Kyrgyz som",
    symbol: "сом",
    iso4217: "KGS",
    factionalUnit: "Tyiyn",
  },
  {
    name: "Lao kip",
    symbol: "₭",
    iso4217: "LAK",
    factionalUnit: "Att",
  },
  {
    name: "Lebanese pound",
    symbol: "LL",
    iso4217: "LBP",
  },
  {
    name: "Lesotho loti",
    symbol: "L",
    iso4217: "LSL",
    factionalUnit: "Sente",
  },
  {
    name: "Liberian dollar",
    symbol: "$",
    iso4217: "LRD",
    factionalUnit: "Cent",
  },
  {
    name: "Libyan dinar",
    symbol: "LD",
    iso4217: "LYD",
    factionalUnit: "Dirham",
  },
  {
    name: "Swiss franc",
    symbol: "Fr",
    iso4217: "CHF",
    factionalUnit: "Rappen",
  },
  {
    name: "Macanese pataca",
    symbol: "ptc",
    iso4217: "MOP",
  },
  {
    name: "Malagasy ariary",
    symbol: "Ar",
    iso4217: "MGA",
    factionalUnit: "Iraimbilanja",
  },
  {
    name: "Malawian kwacha",
    symbol: "K",
    iso4217: "MWK",
    factionalUnit: "Tambala",
  },
  {
    name: "Malaysian ringgit",
    symbol: "RM",
    iso4217: "MYR",
    factionalUnit: "Sen",
  },
  {
    name: "Maldivian rufiyaa",
    symbol: "Rf",
    iso4217: "MVR",
    factionalUnit: "Laari",
  },
  {
    name: "Mauritanian ouguiya",
    symbol: "UM",
    iso4217: "MRU",
    factionalUnit: "Khoums",
  },
  {
    name: "Mauritian rupee",
    symbol: "Re",
    iso4217: "MUR",
    factionalUnit: "Cent",
  },
  {
    name: "Mexican peso",
    symbol: "Mx$",
    iso4217: "MXN",
    factionalUnit: "Centavo",
  },
  {
    name: "Moldovan leu",
    symbol: "Leu",
    iso4217: "MDL",
    factionalUnit: "Ban",
  },
  {
    name: "Mongolian tögrög",
    symbol: "₮",
    iso4217: "MNT",
    factionalUnit: "Möngö",
  },
  {
    name: "Moroccan dirham",
    symbol: "DH",
    iso4217: "MAD",
    factionalUnit: "Centime",
  },
  {
    name: "Mozambican metical",
    symbol: "Mt",
    iso4217: "MZN",
    factionalUnit: "Centavo",
  },
  {
    name: "Burmese kyat",
    symbol: "K",
    iso4217: "MMK",
  },
  {
    name: "Namibian dollar",
    symbol: "$",
    iso4217: "NAD",
    factionalUnit: "Cent",
  },
  {
    name: "Nepalese rupee",
    symbol: "रु",
    iso4217: "NPR",
    factionalUnit: "Paisa",
  },
  {
    name: "Nicaraguan córdoba",
    symbol: "C$",
    iso4217: "NIO",
    factionalUnit: "Centavo",
  },
  {
    name: "Nigerian naira",
    symbol: "₦",
    iso4217: "NGN",
  },
  {
    name: "Macedonian denar",
    symbol: "DEN",
    iso4217: "MKD",
  },
  {
    name: "Turkish lira",
    symbol: "₺",
    iso4217: "TRY",
  },
  {
    name: "Norwegian krone",
    symbol: "kr",
    iso4217: "NOK",
    factionalUnit: "Øre",
  },
  {
    name: "Omani rial",
    symbol: "RO",
    iso4217: "OMR",
  },
  {
    name: "Pakistani rupee",
    symbol: "Rs",
    iso4217: "PKR",
    factionalUnit: "Paisa",
  },
  {
    name: "Panamanian balboa",
    symbol: "B/",
    iso4217: "PAB",
  },
  {
    name: "Papua New Guinean kina",
    symbol: "K",
    iso4217: "PGK",
  },
  {
    name: "Paraguayan guaraní",
    symbol: "₲",
    iso4217: "PYG",
    factionalUnit: "Céntimo",
  },
  {
    name: "Peruvian sol",
    symbol: "S/",
    iso4217: "PEN",
    factionalUnit: "Céntimo",
  },
  {
    name: "Philippine peso",
    symbol: "₱",
    iso4217: "PHP",
    factionalUnit: "Sentimo",
  },
  {
    name: "Polish złoty",
    symbol: "zł",
    iso4217: "PLN",
    factionalUnit: "Grosz",
  },
  {
    name: "Qatari riyal",
    symbol: "QR",
    iso4217: "QAR",
    factionalUnit: "Dirham",
  },
  {
    name: "Romanian leu",
    symbol: "Lei",
    iso4217: "RON",
    factionalUnit: "Ban",
  },
  {
    name: "Russian ruble",
    symbol: "₽",
    iso4217: "RUB",
    factionalUnit: "Kopeck",
  },
  {
    name: "Rwandan franc",
    symbol: "FRw",
    iso4217: "RWF",
    factionalUnit: "Centime",
  },
  {
    name: "Samoan tālā",
    symbol: "T$",
    iso4217: "WST",
  },
  {
    name: "São Tomé and Príncipe dobra",
    symbol: "Db",
    iso4217: "STN",
    factionalUnit: "Cêntimo",
  },
  {
    name: "Saudi riyal",
    symbol: "﷼",
    iso4217: "SAR",
  },
  {
    name: "Serbian dinar",
    symbol: "DIN",
    iso4217: "RSD",
  },
  {
    name: "Seychellois rupee",
    symbol: "Re",
    iso4217: "SCR",
    factionalUnit: "Cent",
  },
  {
    name: "Sierra Leonean leone",
    symbol: "Le",
    iso4217: "SLE",
    factionalUnit: "Cent",
  },
  {
    name: "Solomon Islands dollar",
    symbol: "SBD",
    iso4217: "SBD",
    factionalUnit: "Cent",
  },
  {
    name: "Somali shilling",
    symbol: "SOS",
    iso4217: "SOS",
    factionalUnit: "Cent",
  },
  {
    name: "South Sudanese pound",
    symbol: "SS£",
    iso4217: "SSP",
  },
  {
    name: "Sri Lankan rupee",
    symbol: "Re",
    iso4217: "LKR",
    factionalUnit: "Cent",
  },
  {
    name: "Sudanese pound",
    symbol: "LS",
    iso4217: "SDG",
  },
  {
    name: "Surinamese dollar",
    symbol: "$",
    iso4217: "SRD",
    factionalUnit: "Cent",
  },
  {
    name: "Swedish krona",
    symbol: "SEK",
    iso4217: "SEK",
    factionalUnit: "Øre",
  },
  {
    name: "Syrian pound",
    symbol: "SYP",
    iso4217: "SYP",
  },
  {
    name: "New Taiwan dollar",
    symbol: "NT$",
    iso4217: "TWD",
    factionalUnit: "Cent",
  },
  {
    name: "Tajikistani somoni",
    symbol: "SM",
    iso4217: "TJS",
    factionalUnit: "Diram",
  },
  {
    name: "Tanzanian shilling",
    symbol: "Shs",
    iso4217: "TZS",
    factionalUnit: "Cent",
  },
  {
    name: "Thai baht",
    symbol: "฿",
    iso4217: "THB",
    factionalUnit: "Satang",
  },
  {
    name: "Tongan paʻanga",
    symbol: "T$",
    iso4217: "TOP",
  },
  {
    name: "Trinidad and Tobago dollar",
    symbol: "T$",
    iso4217: "TTD",
    factionalUnit: "Cent",
  },
  {
    name: "Tunisian dinar",
    symbol: "DT",
    iso4217: "TND",
  },
  {
    name: "Turkmenistani manat",
    symbol: "m",
    iso4217: "TMT",
  },
  {
    name: "Ugandan shilling",
    symbol: "Sh",
    iso4217: "UGX",
  },
  {
    name: "Ukrainian hryvnia",
    symbol: "₴",
    iso4217: "UAH",
    factionalUnit: "Kopeck",
  },
  {
    name: "United Arab Emirates dirham",
    symbol: "AED",
    iso4217: "AED",
    factionalUnit: "Fils",
  },
  {
    name: "Uruguayan peso",
    symbol: "UYU",
    iso4217: "UYU",
  },
  {
    name: "Uzbekistani sum",
    symbol: "Sʻ",
    iso4217: "UZS",
  },
  {
    name: "Vanuatu vatu",
    symbol: "VT",
    iso4217: "VUV",
    factionalUnit: "Cent",
  },
  {
    name: "Venezuelan sovereign bolívar",
    symbol: "Bs.S",
    iso4217: "VES",
    factionalUnit: "Céntimo",
  },
  {
    name: "Venezuelan digital bolívar",
    symbol: "Bs.D",
    iso4217: "VED",
    factionalUnit: "Céntimo",
  },
  {
    name: "Vietnamese đồng",
    symbol: "₫",
    iso4217: "VND",
  },
  {
    name: "Yemeni rial",
    symbol: "YER",
    iso4217: "YER",
    factionalUnit: "Fils",
  },
  {
    name: "Zambian kwacha",
    symbol: "ZMW",
    iso4217: "ZMW",
    factionalUnit: "Ngwee",
  },
  {
    name: "Zimbabwe gold",
    symbol: "ZiG",
    iso4217: "ZWG",
  },
];
