import type { ISO3166 } from "./iso-3166";
import type { Continent, Region } from "./types";

export const countries: Array<ISO3166> = [
  {
    name: "Afghanistan",
    alpha2: "AF",
    alpha3: "AFG",
    numeric: "004",
    continents: ["Asia"],
    regions: ["APAC", "MEA"],
    dialects: [
      { dialect: "Dari", native: "دری", iso639_1: "fa", bcp47: "fa-AF" }, // Dari is a dialect of Persian (fa)
      { dialect: "Pashto", native: "پښتو", iso639_1: "ps", bcp47: "ps-AF" },
    ],
  },
  {
    name: "Albania",
    alpha2: "AL",
    alpha3: "ALB",
    numeric: "008",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Albanian", native: "Shqip", iso639_1: "sq", bcp47: "sq-AL" },
    ],
  },
  {
    name: "Algeria",
    alpha2: "DZ",
    alpha3: "DZA",
    numeric: "012",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-DZ" },
      // While Berber is widely spoken, "Berber" is a language family.
      // For more specific dialect, a different ISO code might be needed or a broader BCP47 tag.
      // Leaving it out for now to adhere strictly to singular languages with iso639_1 codes.
    ],
  },
  {
    name: "American Samoa",
    alpha2: "AS",
    alpha3: "ASM",
    numeric: "016",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-AS",
      },
      {
        dialect: "Samoan",
        native: "Gagana Sāmoa",
        iso639_1: "sm",
        bcp47: "sm-AS",
      },
    ],
  },
  {
    name: "Andorra",
    alpha2: "AD",
    alpha3: "AND",
    numeric: "020",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Catalan", native: "Català", iso639_1: "ca", bcp47: "ca-AD" },
    ],
  },
  {
    name: "Angola",
    alpha2: "AO",
    alpha3: "AGO",
    numeric: "024",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Portuguese",
        native: "Português",
        iso639_1: "pt",
        bcp47: "pt-AO",
      },
    ],
  },
  {
    name: "Anguilla",
    alpha2: "AI",
    alpha3: "AIA",
    numeric: "660",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-AI",
      },
    ],
  },
  {
    name: "Antarctica",
    alpha2: "AQ",
    alpha3: "ATA",
    numeric: "010",
    continents: ["Antarctica"],
    regions: [],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-AQ",
      },
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-AQ",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-AQ",
      },
      {
        dialect: "Russian",
        native: "русский язык",
        iso639_1: "ru",
        bcp47: "ru-AQ",
      },
    ],
  },
  {
    name: "Antigua and Barbuda",
    alpha2: "AG",
    alpha3: "ATG",
    numeric: "028",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-AG",
      },
    ],
  },
  {
    name: "Argentina",
    alpha2: "AR",
    alpha3: "ARG",
    numeric: "032",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-AR",
      },
    ],
  },
  {
    name: "Armenia",
    alpha2: "AM",
    alpha3: "ARM",
    numeric: "051",
    continents: ["Asia", "Europe"],
    regions: ["EMEA", "APAC"],
    dialects: [
      {
        dialect: "Armenian",
        native: "Հայերեն",
        iso639_1: "hy",
        bcp47: "hy-AM",
      },
    ],
  },
  {
    name: "Aruba",
    alpha2: "AW",
    alpha3: "ABW",
    numeric: "533",
    continents: ["South America", "Europe"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Dutch",
        native: "Nederlands",
        iso639_1: "nl",
        bcp47: "nl-AW",
      },
      {
        dialect: "Papiamento",
        native: "Papiamentu",
        iso639_3: "pap",
        bcp47: "pap-AW",
      }, // ISO 639-3 code, as it doesn't have 639-1
    ],
  },
  {
    name: "Australia",
    alpha2: "AU",
    alpha3: "AUS",
    numeric: "036",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-AU",
      },
    ],
  },
  {
    name: "Austria",
    alpha2: "AT",
    alpha3: "AUT",
    numeric: "040",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "German", native: "Deutsch", iso639_1: "de", bcp47: "de-AT" },
    ],
  },
  {
    name: "Azerbaijan",
    alpha2: "AZ",
    alpha3: "AZE",
    numeric: "031",
    continents: ["Asia", "Europe"],
    regions: ["EMEA", "APAC"],
    dialects: [
      {
        dialect: "Azerbaijani",
        native: "Azərbaycan dili",
        iso639_1: "az",
        bcp47: "az-AZ",
      },
    ],
  },
  {
    name: "Bahamas",
    alpha2: "BS",
    alpha3: "BHS",
    numeric: "044",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-BS",
      },
    ],
  },
  {
    name: "Bahrain",
    alpha2: "BH",
    alpha3: "BHR",
    numeric: "048",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-BH" },
    ],
  },
  {
    name: "Bangladesh",
    alpha2: "BD",
    alpha3: "BGD",
    numeric: "050",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      { dialect: "Bengali", native: "বাংলা", iso639_1: "bn", bcp47: "bn-BD" },
    ],
  },
  {
    name: "Barbados",
    alpha2: "BB",
    alpha3: "BRB",
    numeric: "052",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-BB",
      },
    ],
  },
  {
    name: "Belarus",
    alpha2: "BY",
    alpha3: "BLR",
    numeric: "112",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Belarusian",
        native: "беларуская мова",
        iso639_1: "be",
        bcp47: "be-BY",
      },
      {
        dialect: "Russian",
        native: "русский язык",
        iso639_1: "ru",
        bcp47: "ru-BY",
      },
    ],
  },
  {
    name: "Belgium",
    alpha2: "BE",
    alpha3: "BEL",
    numeric: "056",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Dutch",
        native: "Nederlands",
        iso639_1: "nl",
        bcp47: "nl-BE",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-BE",
      },
      { dialect: "German", native: "Deutsch", iso639_1: "de", bcp47: "de-BE" },
    ],
  },
  {
    name: "Belize",
    alpha2: "BZ",
    alpha3: "BLZ",
    numeric: "084",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-BZ",
      },
    ],
  },
  {
    name: "Benin",
    alpha2: "BJ",
    alpha3: "BEN",
    numeric: "204",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-BJ",
      },
    ],
  },
  {
    name: "Bermuda",
    alpha2: "BM",
    alpha3: "BMU",
    numeric: "060",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-BM",
      },
    ],
  },
  {
    name: "Bhutan",
    alpha2: "BT",
    alpha3: "BTN",
    numeric: "064",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Dzongkha",
        native: "རྫོང་ཁ",
        iso639_1: "dz",
        bcp47: "dz-BT",
      },
    ],
  },
  {
    name: "Plurinational State of Bolivia",
    alpha2: "BO",
    alpha3: "BOL",
    numeric: "068",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-BO",
      },
      {
        dialect: "Quechua",
        native: "Runa simi",
        iso639_1: "qu",
        bcp47: "qu-BO",
      },
      {
        dialect: "Aymara",
        native: "Aymar aru",
        iso639_1: "ay",
        bcp47: "ay-BO",
      },
      {
        dialect: "Guarani",
        native: "Avañe'ẽ",
        iso639_1: "gn",
        bcp47: "gn-BO",
      },
      // Bolivia has 37 official languages, adding major ones.
    ],
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    alpha2: "BQ",
    alpha3: "BES",
    numeric: "535",
    continents: ["South America", "Europe"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Dutch",
        native: "Nederlands",
        iso639_1: "nl",
        bcp47: "nl-BQ",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-BQ",
      },
    ],
  },
  {
    name: "Bosnia and Herzegovina",
    alpha2: "BA",
    alpha3: "BIH",
    numeric: "070",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Bosnian",
        native: "bosanski",
        iso639_1: "bs",
        bcp47: "bs-BA",
      },
      {
        dialect: "Croatian",
        native: "hrvatski",
        iso639_1: "hr",
        bcp47: "hr-BA",
      },
      {
        dialect: "Serbian",
        native: "српски језик",
        iso639_1: "sr",
        bcp47: "sr-BA",
      },
    ],
  },
  {
    name: "Botswana",
    alpha2: "BW",
    alpha3: "BWA",
    numeric: "072",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-BW",
      },
      {
        dialect: "Tswana",
        native: "Setswana",
        iso639_1: "tn",
        bcp47: "tn-BW",
      },
    ],
  },
  {
    name: "Bouvet Island",
    alpha2: "BV",
    alpha3: "BVT",
    numeric: "074",
    continents: ["Antarctica"],
    regions: [],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-BV",
      },
    ],
  },
  {
    name: "Brazil",
    alpha2: "BR",
    alpha3: "BRA",
    numeric: "076",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Portuguese",
        native: "Português",
        iso639_1: "pt",
        bcp47: "pt-BR",
      },
    ],
  },
  {
    name: "British Indian Ocean Territory",
    alpha2: "IO",
    alpha3: "IOT",
    numeric: "086",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-IO",
      },
    ],
  },
  {
    name: "Brunei Darussalam",
    alpha2: "BN",
    alpha3: "BRN",
    numeric: "096",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Malay",
        native: "Bahasa Melayu",
        iso639_1: "ms",
        bcp47: "ms-BN",
      },
    ],
  },
  {
    name: "Bulgaria",
    alpha2: "BG",
    alpha3: "BGR",
    numeric: "100",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Bulgarian",
        native: "български език",
        iso639_1: "bg",
        bcp47: "bg-BG",
      },
    ],
  },
  {
    name: "Burkina Faso",
    alpha2: "BF",
    alpha3: "BFA",
    numeric: "854",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-BF",
      },
    ],
  },
  {
    name: "Burundi",
    alpha2: "BI",
    alpha3: "BDI",
    numeric: "108",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Kirundi",
        native: "Ikirundi",
        iso639_1: "rn",
        bcp47: "rn-BI",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-BI",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-BI",
      },
    ],
  },
  {
    name: "Cape Verde",
    alpha2: "CV",
    alpha3: "CPV",
    numeric: "132",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Portuguese",
        native: "Português",
        iso639_1: "pt",
        bcp47: "pt-CV",
      },
    ],
  },
  {
    name: "Cambodia",
    alpha2: "KH",
    alpha3: "KHM",
    numeric: "116",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Central Khmer",
        native: "ភាសាខ្មែរ",
        iso639_1: "km",
        bcp47: "km-KH",
      },
    ],
  },
  {
    name: "Cameroon",
    alpha2: "CM",
    alpha3: "CMR",
    numeric: "120",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-CM",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-CM",
      },
    ],
  },
  {
    name: "Canada",
    alpha2: "CA",
    alpha3: "CAN",
    numeric: "124",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-CA",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-CA",
      },
    ],
  },
  {
    name: "Cayman Islands",
    alpha2: "KY",
    alpha3: "CYM",
    numeric: "136",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-KY",
      },
    ],
  },
  {
    name: "Central African Republic",
    alpha2: "CF",
    alpha3: "CAF",
    numeric: "140",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-CF",
      },
      { dialect: "Sango", native: "Sängö", iso639_1: "sg", bcp47: "sg-CF" },
    ],
  },
  {
    name: "Chad",
    alpha2: "TD",
    alpha3: "TCD",
    numeric: "148",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-TD" },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-TD",
      },
    ],
  },
  {
    name: "Chile",
    alpha2: "CL",
    alpha3: "CHL",
    numeric: "152",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-CL",
      },
    ],
  },
  {
    name: "China",
    alpha2: "CN",
    alpha3: "CHN",
    numeric: "156",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Chinese",
        native: "中文",
        iso639_1: "zh",
        bcp47: "zh-Hans-CN",
      }, // Simplified Chinese for Mainland China
    ],
  },
  {
    name: "Christmas Island",
    alpha2: "CX",
    alpha3: "CXR",
    numeric: "162",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-CX",
      },
    ],
  },
  {
    name: "Cocos (Keeling) Islands",
    alpha2: "CC",
    alpha3: "CCK",
    numeric: "166",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-CC",
      },
    ],
  },
  {
    name: "Colombia",
    alpha2: "CO",
    alpha3: "COL",
    numeric: "170",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-CO",
      },
    ],
  },
  {
    name: "Comoros",
    alpha2: "KM",
    alpha3: "COM",
    numeric: "174",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Comorian",
        native: "Shimasiwa",
        iso639_1: "ar",
        bcp47: "ar-KM",
      }, // Comorian is derived from Arabic, no direct 639-1 code
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-KM",
      },
    ],
  },
  {
    name: "Congo", // Republic of the Congo
    alpha2: "CG",
    alpha3: "COG",
    numeric: "178",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-CG",
      },
      {
        dialect: "Lingala",
        native: "Lingála",
        iso639_1: "ln",
        bcp47: "ln-CG",
      },
      { dialect: "Kongo", native: "Kikongo", iso639_1: "kg", bcp47: "kg-CG" },
    ],
  },
  {
    name: "Democratic Republic of Congo",
    alpha2: "CD",
    alpha3: "COD",
    numeric: "180",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-CD",
      },
      {
        dialect: "Lingala",
        native: "Lingála",
        iso639_1: "ln",
        bcp47: "ln-CD",
      },
      { dialect: "Kongo", native: "Kikongo", iso639_1: "kg", bcp47: "kg-CD" },
      {
        dialect: "Swahili",
        native: "Kiswahili",
        iso639_1: "sw",
        bcp47: "sw-CD",
      },
      {
        dialect: "Luba-Katanga",
        native: "Tshiluba",
        iso639_1: "lu",
        bcp47: "lu-CD",
      },
    ],
  },
  {
    name: "Cook Islands",
    alpha2: "CK",
    alpha3: "COK",
    numeric: "184",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-CK",
      },
      // Cook Islands Māori (Rarotongan) - no direct ISO 639-1
    ],
  },
  {
    name: "Costa Rica",
    alpha2: "CR",
    alpha3: "CRI",
    numeric: "188",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-CR",
      },
    ],
  },
  {
    name: "Côte d'Ivoire",
    alpha2: "CI",
    alpha3: "CIV",
    numeric: "384",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-CI",
      },
    ],
  },
  {
    name: "Croatia",
    alpha2: "HR",
    alpha3: "HRV",
    numeric: "191",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Croatian",
        native: "hrvatski",
        iso639_1: "hr",
        bcp47: "hr-HR",
      },
    ],
  },
  {
    name: "Cuba",
    alpha2: "CU",
    alpha3: "CUB",
    numeric: "192",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-CU",
      },
    ],
  },
  {
    name: "Curaçao",
    alpha2: "CW",
    alpha3: "CUW",
    numeric: "531",
    continents: ["South America", "Europe"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Dutch",
        native: "Nederlands",
        iso639_1: "nl",
        bcp47: "nl-CW",
      },
      {
        dialect: "Papiamento",
        native: "Papiamentu",
        iso639_3: "pap",
        bcp47: "pap-CW",
      }, // ISO 639-3 code, as it doesn't have 639-1
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-CW",
      },
    ],
  },
  {
    name: "Cyprus",
    alpha2: "CY",
    alpha3: "CYP",
    numeric: "196",
    continents: ["Europe", "Asia"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Greek", native: "Ελληνικά", iso639_1: "el", bcp47: "el-CY" },
      { dialect: "Turkish", native: "Türkçe", iso639_1: "tr", bcp47: "tr-CY" },
    ],
  },
  {
    name: "Czechia",
    alpha2: "CZ",
    alpha3: "CZE",
    numeric: "203",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Czech", native: "čeština", iso639_1: "cs", bcp47: "cs-CZ" },
    ],
  },
  {
    name: "Denmark",
    alpha2: "DK",
    alpha3: "DNK",
    numeric: "208",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Danish", native: "Dansk", iso639_1: "da", bcp47: "da-DK" },
    ],
  },
  {
    name: "Djibouti",
    alpha2: "DJ",
    alpha3: "DJI",
    numeric: "262",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-DJ" },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-DJ",
      },
      {
        dialect: "Somali",
        native: "Af Soomaali",
        iso639_1: "so",
        bcp47: "so-DJ",
      },
      { dialect: "Afar", native: "Qafar af", iso639_1: "aa", bcp47: "aa-DJ" },
    ],
  },
  {
    name: "Dominica",
    alpha2: "DM",
    alpha3: "DMA",
    numeric: "212",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-DM",
      },
    ],
  },
  {
    name: "Dominican Republic",
    alpha2: "DO",
    alpha3: "DOM",
    numeric: "214",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-DO",
      },
    ],
  },
  {
    name: "Ecuador",
    alpha2: "EC",
    alpha3: "ECU",
    numeric: "218",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-EC",
      },
      {
        dialect: "Quechua",
        native: "Runa simi",
        iso639_1: "qu",
        bcp47: "qu-EC",
      },
    ],
  },
  {
    name: "Egypt",
    alpha2: "EG",
    alpha3: "EGY",
    numeric: "818",
    continents: ["Africa", "Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-EG" },
    ],
  },
  {
    name: "El Salvador",
    alpha2: "SV",
    alpha3: "SLV",
    numeric: "222",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-SV",
      },
    ],
  },
  {
    name: "Equatorial Guinea",
    alpha2: "GQ",
    alpha3: "GNQ",
    numeric: "226",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-GQ",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-GQ",
      },
      {
        dialect: "Portuguese",
        native: "Português",
        iso639_1: "pt",
        bcp47: "pt-GQ",
      },
    ],
  },
  {
    name: "Eritrea",
    alpha2: "ER",
    alpha3: "ERI",
    numeric: "232",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Tigrinya", native: "ትግርኛ", iso639_1: "ti", bcp47: "ti-ER" },
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-ER" },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-ER",
      },
    ],
  },
  {
    name: "Estonia",
    alpha2: "EE",
    alpha3: "EST",
    numeric: "233",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Estonian",
        native: "eesti keel",
        iso639_1: "et",
        bcp47: "et-EE",
      },
    ],
  },
  {
    name: "Eswatini",
    alpha2: "SZ",
    alpha3: "SWZ",
    numeric: "748",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-SZ",
      },
      { dialect: "Swati", native: "SiSwati", iso639_1: "ss", bcp47: "ss-SZ" },
    ],
  },
  {
    name: "Ethiopia",
    alpha2: "ET",
    alpha3: "ETH",
    numeric: "231",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Amharic", native: "አማርኛ", iso639_1: "am", bcp47: "am-ET" },
      {
        dialect: "Oromo",
        native: "Afaan Oromoo",
        iso639_1: "om",
        bcp47: "om-ET",
      },
      { dialect: "Tigrinya", native: "ትግርኛ", iso639_1: "ti", bcp47: "ti-ET" },
    ],
  },
  {
    name: "Falkland Islands",
    alpha2: "FK",
    alpha3: "FLK",
    numeric: "238",
    continents: ["South America"],
    regions: ["AMER", "SA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-FK",
      },
    ],
  },
  {
    name: "Faroe Islands",
    alpha2: "FO",
    alpha3: "FRO",
    numeric: "234",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Faroese",
        native: "føroyskt",
        iso639_1: "fo",
        bcp47: "fo-FO",
      },
      { dialect: "Danish", native: "Dansk", iso639_1: "da", bcp47: "da-FO" },
    ],
  },
  {
    name: "Fiji",
    alpha2: "FJ",
    alpha3: "FJI",
    numeric: "242",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-FJ",
      },
      {
        dialect: "Fijian",
        native: "Na Vosa Vakaviti",
        iso639_1: "fj",
        bcp47: "fj-FJ",
      },
    ],
  },
  {
    name: "Finland",
    alpha2: "FI",
    alpha3: "FIN",
    numeric: "246",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Finnish", native: "suomi", iso639_1: "fi", bcp47: "fi-FI" },
      {
        dialect: "Swedish",
        native: "Svenska",
        iso639_1: "sv",
        bcp47: "sv-FI",
      },
    ],
  },
  {
    name: "France",
    alpha2: "FR",
    alpha3: "FRA",
    numeric: "250",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-FR",
      },
    ],
  },
  {
    name: "French Guiana",
    alpha2: "GF",
    alpha3: "GUF",
    numeric: "254",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-GF",
      },
    ],
  },
  {
    name: "French Polynesia",
    alpha2: "PF",
    alpha3: "PYF",
    numeric: "258",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-PF",
      },
      {
        dialect: "Tahitian",
        native: "Reo Tahiti",
        iso639_1: "ty",
        bcp47: "ty-PF",
      }, // ISO 639-2/3
    ],
  },
  {
    name: "French Southern Territories",
    alpha2: "TF",
    alpha3: "ATF",
    numeric: "260",
    continents: ["Antarctica"],
    regions: [],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-TF",
      },
    ],
  },
  {
    name: "Gabon",
    alpha2: "GA",
    alpha3: "GAB",
    numeric: "266",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-GA",
      },
    ],
  },
  {
    name: "Gambia",
    alpha2: "GM",
    alpha3: "GMB",
    numeric: "270",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-GM",
      },
    ],
  },
  {
    name: "Georgia",
    alpha2: "GE",
    alpha3: "GEO",
    numeric: "268",
    continents: ["Asia", "Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Georgian",
        native: "ქართული",
        iso639_1: "ka",
        bcp47: "ka-GE",
      },
    ],
  },
  {
    name: "Germany",
    alpha2: "DE",
    alpha3: "DEU",
    numeric: "276",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "German", native: "Deutsch", iso639_1: "de", bcp47: "de-DE" },
    ],
  },
  {
    name: "Ghana",
    alpha2: "GH",
    alpha3: "GHA",
    numeric: "288",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-GH",
      },
    ],
  },
  {
    name: "Gibraltar",
    alpha2: "GI",
    alpha3: "GIB",
    numeric: "292",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-GI",
      },
    ],
  },
  {
    name: "Greece",
    alpha2: "GR",
    alpha3: "GRC",
    numeric: "300",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Greek", native: "Ελληνικά", iso639_1: "el", bcp47: "el-GR" },
    ],
  },
  {
    name: "Greenland",
    alpha2: "GL",
    alpha3: "GRL",
    numeric: "304",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: [
      {
        dialect: "Kalaallisut",
        native: "kalaallisut",
        iso639_1: "kl",
        bcp47: "kl-GL",
      },
      { dialect: "Danish", native: "Dansk", iso639_1: "da", bcp47: "da-GL" },
    ],
  },
  {
    name: "Grenada",
    alpha2: "GD",
    alpha3: "GRD",
    numeric: "308",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-GD",
      },
    ],
  },
  {
    name: "Guadeloupe",
    alpha2: "GP",
    alpha3: "GLP",
    numeric: "312",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-GP",
      },
    ],
  },
  {
    name: "Guam",
    alpha2: "GU",
    alpha3: "GUM",
    numeric: "316",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-GU",
      },
      {
        dialect: "Chamorro",
        native: "Finuʼ Chamoru",
        iso639_1: "ch",
        bcp47: "ch-GU",
      },
    ],
  },
  {
    name: "Guatemala",
    alpha2: "GT",
    alpha3: "GTM",
    numeric: "320",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-GT",
      },
    ],
  },
  {
    name: "Guernsey",
    alpha2: "GG",
    alpha3: "GGY",
    numeric: "831",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-GG",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-GG",
      },
    ],
  },
  {
    name: "Guinea",
    alpha2: "GN",
    alpha3: "GIN",
    numeric: "324",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-GN",
      },
    ],
  },
  {
    name: "Guinea-Bissau",
    alpha2: "GW",
    alpha3: "GNB",
    numeric: "624",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Portuguese",
        native: "Português",
        iso639_1: "pt",
        bcp47: "pt-GW",
      },
    ],
  },
  {
    name: "Guyana",
    alpha2: "GY",
    alpha3: "GUY",
    numeric: "328",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-GY",
      },
    ],
  },
  {
    name: "Haiti",
    alpha2: "HT",
    alpha3: "HTI",
    numeric: "332",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Haitian",
        native: "Kreyòl ayisyen",
        iso639_1: "ht",
        bcp47: "ht-HT",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-HT",
      },
    ],
  },
  {
    name: "Heard Island and McDonald Islands",
    alpha2: "HM",
    alpha3: "HMD",
    numeric: "334",
    continents: ["Antarctica"],
    regions: [],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-HM",
      },
    ],
  },
  {
    name: "Holy See",
    alpha2: "VA",
    alpha3: "VAT",
    numeric: "336",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Latin", native: "Latina", iso639_1: "la", bcp47: "la-VA" },
      {
        dialect: "Italian",
        native: "Italiano",
        iso639_1: "it",
        bcp47: "it-VA",
      },
    ],
  },
  {
    name: "Honduras",
    alpha2: "HN",
    alpha3: "HND",
    numeric: "340",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-HN",
      },
    ],
  },
  {
    name: "Hong Kong",
    alpha2: "HK",
    alpha3: "HKG",
    numeric: "344",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Chinese",
        native: "中文",
        iso639_1: "zh",
        bcp47: "zh-Hant-HK",
      }, // Traditional Chinese for Hong Kong
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-HK",
      },
    ],
  },
  {
    name: "Hungary",
    alpha2: "HU",
    alpha3: "HUN",
    numeric: "348",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Hungarian",
        native: "Magyar",
        iso639_1: "hu",
        bcp47: "hu-HU",
      },
    ],
  },
  {
    name: "Iceland",
    alpha2: "IS",
    alpha3: "ISL",
    numeric: "352",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Icelandic",
        native: "íslenska",
        iso639_1: "is",
        bcp47: "is-IS",
      },
    ],
  },
  {
    name: "India",
    alpha2: "IN",
    alpha3: "IND",
    numeric: "356",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      { dialect: "Hindi", native: "हिन्दी", iso639_1: "hi", bcp47: "hi-IN" },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-IN",
      },
      // India has many official languages, including Bengali, Marathi, Telugu, Tamil, Gujarati, etc.
      // For brevity, only the two federal official languages are included.
    ],
  },
  {
    name: "Indonesia",
    alpha2: "ID",
    alpha3: "IDN",
    numeric: "360",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Indonesian",
        native: "Bahasa Indonesia",
        iso639_1: "id",
        bcp47: "id-ID",
      },
    ],
  },
  {
    name: "Iran (Islamic Republic of)",
    alpha2: "IR",
    alpha3: "IRN",
    numeric: "364",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Persian", native: "فارسی", iso639_1: "fa", bcp47: "fa-IR" },
    ],
  },
  {
    name: "Iraq",
    alpha2: "IQ",
    alpha3: "IRQ",
    numeric: "368",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-IQ" },
      { dialect: "Kurdish", native: "Kurdî", iso639_1: "ku", bcp47: "ku-IQ" },
    ],
  },
  {
    name: "Ireland",
    alpha2: "IE",
    alpha3: "IRL",
    numeric: "372",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Irish", native: "Gaeilge", iso639_1: "ga", bcp47: "ga-IE" },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-IE",
      },
    ],
  },
  {
    name: "Isle of Man",
    alpha2: "IM",
    alpha3: "IMN",
    numeric: "833",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-IM",
      },
      { dialect: "Manx", native: "Gaelg", iso639_1: "gv", bcp47: "gv-IM" },
    ],
  },
  {
    name: "Israel",
    alpha2: "IL",
    alpha3: "ISR",
    numeric: "376",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Hebrew", native: "עברית", iso639_1: "he", bcp47: "he-IL" },
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-IL" },
    ],
  },
  {
    name: "Italy",
    alpha2: "IT",
    alpha3: "ITA",
    numeric: "380",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Italian",
        native: "Italiano",
        iso639_1: "it",
        bcp47: "it-IT",
      },
    ],
  },
  {
    name: "Jamaica",
    alpha2: "JM",
    alpha3: "JAM",
    numeric: "388",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-JM",
      },
    ],
  },
  {
    name: "Japan",
    alpha2: "JP",
    alpha3: "JPN",
    numeric: "392",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Japanese",
        native: "日本語",
        iso639_1: "ja",
        bcp47: "ja-JP",
      },
    ],
  },
  {
    name: "Jersey",
    alpha2: "JE",
    alpha3: "JEY",
    numeric: "832",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-JE",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-JE",
      },
    ],
  },
  {
    name: "Jordan",
    alpha2: "JO",
    alpha3: "JOR",
    numeric: "400",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-JO" },
    ],
  },
  {
    name: "Kazakhstan",
    alpha2: "KZ",
    alpha3: "KAZ",
    numeric: "398",
    continents: ["Asia", "Europe"],
    regions: ["EMEA", "APAC"],
    dialects: [
      {
        dialect: "Kazakh",
        native: "қазақ тілі",
        iso639_1: "kk",
        bcp47: "kk-KZ",
      },
      {
        dialect: "Russian",
        native: "русский язык",
        iso639_1: "ru",
        bcp47: "ru-KZ",
      },
    ],
  },
  {
    name: "Kenya",
    alpha2: "KE",
    alpha3: "KEN",
    numeric: "404",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Swahili",
        native: "Kiswahili",
        iso639_1: "sw",
        bcp47: "sw-KE",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-KE",
      },
    ],
  },
  {
    name: "Kiribati",
    alpha2: "KI",
    alpha3: "KIR",
    numeric: "296",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-KI",
      },
      {
        dialect: "Gilbertese",
        native: "te taetae ni Kiribati",
        iso639_3: "gil",
        bcp47: "gil-KI",
      }, // ISO 639-3, no 639-1
    ],
  },
  {
    name: "Democratic People's Republic of Korea",
    alpha2: "KP",
    alpha3: "PRK",
    numeric: "408",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      { dialect: "Korean", native: "한국어", iso639_1: "ko", bcp47: "ko-KP" },
    ],
  },
  {
    name: "Republic of Korea",
    alpha2: "KR",
    alpha3: "KOR",
    numeric: "410",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      { dialect: "Korean", native: "한국어", iso639_1: "ko", bcp47: "ko-KR" },
    ],
  },
  {
    name: "Kuwait",
    alpha2: "KW",
    alpha3: "KWT",
    numeric: "414",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-KW" },
    ],
  },
  {
    name: "Kyrgyzstan",
    alpha2: "KG",
    alpha3: "KGZ",
    numeric: "417",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Kyrgyz",
        native: "Кыргызча",
        iso639_1: "ky",
        bcp47: "ky-KG",
      },
      {
        dialect: "Russian",
        native: "русский язык",
        iso639_1: "ru",
        bcp47: "ru-KG",
      },
    ],
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2: "LA",
    alpha3: "LAO",
    numeric: "418",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      { dialect: "Lao", native: "ພາສາລາວ", iso639_1: "lo", bcp47: "lo-LA" },
    ],
  },
  {
    name: "Latvia",
    alpha2: "LV",
    alpha3: "LVA",
    numeric: "428",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Latvian",
        native: "latviešu valoda",
        iso639_1: "lv",
        bcp47: "lv-LV",
      },
    ],
  },
  {
    name: "Lebanon",
    alpha2: "LB",
    alpha3: "LBN",
    numeric: "422",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-LB" },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-LB",
      },
    ],
  },
  {
    name: "Lesotho",
    alpha2: "LS",
    alpha3: "LSO",
    numeric: "426",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Southern Sotho",
        native: "Sesotho",
        iso639_1: "st",
        bcp47: "st-LS",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-LS",
      },
    ],
  },
  {
    name: "Liberia",
    alpha2: "LR",
    alpha3: "LBR",
    numeric: "430",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-LR",
      },
    ],
  },
  {
    name: "Libya",
    alpha2: "LY",
    alpha3: "LBY",
    numeric: "434",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-LY" },
    ],
  },
  {
    name: "Liechtenstein",
    alpha2: "LI",
    alpha3: "LIE",
    numeric: "438",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "German", native: "Deutsch", iso639_1: "de", bcp47: "de-LI" },
    ],
  },
  {
    name: "Lithuania",
    alpha2: "LT",
    alpha3: "LTU",
    numeric: "440",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Lithuanian",
        native: "lietuvių kalba",
        iso639_1: "lt",
        bcp47: "lt-LT",
      },
    ],
  },
  {
    name: "Luxembourg",
    alpha2: "LU",
    alpha3: "LUX",
    numeric: "442",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Luxembourgish",
        native: "Lëtzebuergesch",
        iso639_1: "lb",
        bcp47: "lb-LU",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-LU",
      },
      { dialect: "German", native: "Deutsch", iso639_1: "de", bcp47: "de-LU" },
    ],
  },
  {
    name: "Macao",
    alpha2: "MO",
    alpha3: "MAC",
    numeric: "446",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Chinese",
        native: "中文",
        iso639_1: "zh",
        bcp47: "zh-Hant-MO",
      }, // Traditional Chinese for Macao
      {
        dialect: "Portuguese",
        native: "Português",
        iso639_1: "pt",
        bcp47: "pt-MO",
      },
    ],
  },
  {
    name: "Madagascar",
    alpha2: "MG",
    alpha3: "MDG",
    numeric: "450",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Malagasy",
        native: "Malagasy fiteny",
        iso639_1: "mg",
        bcp47: "mg-MG",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-MG",
      },
    ],
  },
  {
    name: "Malawi",
    alpha2: "MW",
    alpha3: "MWI",
    numeric: "454",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-MW",
      },
      {
        dialect: "Chichewa",
        native: "Chicheŵa",
        iso639_1: "ny",
        bcp47: "ny-MW",
      },
    ],
  },
  {
    name: "Malaysia",
    alpha2: "MY",
    alpha3: "MYS",
    numeric: "458",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Malay",
        native: "Bahasa Melayu",
        iso639_1: "ms",
        bcp47: "ms-MY",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-MY",
      },
      {
        dialect: "Chinese",
        native: "中文",
        iso639_1: "zh",
        bcp47: "zh-Hans-MY",
      }, // Simplified Chinese
      { dialect: "Tamil", native: "தமிழ்", iso639_1: "ta", bcp47: "ta-MY" },
    ],
  },
  {
    name: "Maldives",
    alpha2: "MV",
    alpha3: "MDV",
    numeric: "462",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Divehi",
        native: "ދިވެހިބަސް",
        iso639_1: "dv",
        bcp47: "dv-MV",
      },
    ],
  },
  {
    name: "Mali",
    alpha2: "ML",
    alpha3: "MLI",
    numeric: "466",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-ML",
      },
    ],
  },
  {
    name: "Malta",
    alpha2: "MT",
    alpha3: "MLT",
    numeric: "470",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Maltese", native: "Malti", iso639_1: "mt", bcp47: "mt-MT" },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-MT",
      },
    ],
  },
  {
    name: "Marshall Islands",
    alpha2: "MH",
    alpha3: "MHL",
    numeric: "584",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Marshallese",
        native: "Kajin M̧ajeļ",
        iso639_1: "mh",
        bcp47: "mh-MH",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-MH",
      },
    ],
  },
  {
    name: "Martinique",
    alpha2: "MQ",
    alpha3: "MTQ",
    numeric: "474",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-MQ",
      },
    ],
  },
  {
    name: "Mauritania",
    alpha2: "MR",
    alpha3: "MRT",
    numeric: "478",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-MR" },
    ],
  },
  {
    name: "Mauritius",
    alpha2: "MU",
    alpha3: "MUS",
    numeric: "480",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-MU",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-MU",
      },
      // Mauritian Creole (mfe) - no 639-1
    ],
  },
  {
    name: "Mayotte",
    alpha2: "YT",
    alpha3: "MYT",
    numeric: "175",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-YT",
      },
    ],
  },
  {
    name: "Mexico",
    alpha2: "MX",
    alpha3: "MEX",
    numeric: "484",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-MX",
      },
    ],
  },
  {
    name: "Micronesia (Federated States of)",
    alpha2: "FM",
    alpha3: "FSM",
    numeric: "583",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-FM",
      },
    ],
  },
  {
    name: "Republic of Moldova",
    alpha2: "MD",
    alpha3: "MDA",
    numeric: "498",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Romanian",
        native: "română",
        iso639_1: "ro",
        bcp47: "ro-MD",
      },
      {
        dialect: "Russian",
        native: "русский язык",
        iso639_1: "ru",
        bcp47: "ru-MD",
      }, // De facto in Transnistria
    ],
  },
  {
    name: "Monaco",
    alpha2: "MC",
    alpha3: "MCO",
    numeric: "492",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-MC",
      },
    ],
  },
  {
    name: "Mongolia",
    alpha2: "MN",
    alpha3: "MNG",
    numeric: "496",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Mongolian",
        native: "Монгол хэл",
        iso639_1: "mn",
        bcp47: "mn-MN",
      },
    ],
  },
  {
    name: "Montenegro",
    alpha2: "ME",
    alpha3: "MNE",
    numeric: "499",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Serbian",
        native: "српски језик",
        iso639_1: "sr",
        bcp47: "sr-ME",
      }, // Montenegrin is a variant of Serbian
    ],
  },
  {
    name: "Montserrat",
    alpha2: "MS",
    alpha3: "MSR",
    numeric: "500",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-MS",
      },
    ],
  },
  {
    name: "Morocco",
    alpha2: "MA",
    alpha3: "MAR",
    numeric: "504",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-MA" },
      {
        dialect: "Berber",
        native: "Tamaziɣt",
        iso639_3: "ber",
        bcp47: "ber-MA",
      }, // Placeholder, no direct ISO 639-1
    ],
  },
  {
    name: "Mozambique",
    alpha2: "MZ",
    alpha3: "MOZ",
    numeric: "508",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Portuguese",
        native: "Português",
        iso639_1: "pt",
        bcp47: "pt-MZ",
      },
    ],
  },
  {
    name: "Myanmar",
    alpha2: "MM",
    alpha3: "MMR",
    numeric: "104",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Burmese",
        native: "မြန်မာဘာသာ",
        iso639_1: "my",
        bcp47: "my-MM",
      },
    ],
  },
  {
    name: "Namibia",
    alpha2: "NA",
    alpha3: "NAM",
    numeric: "516",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-NA",
      },
    ],
  },
  {
    name: "Nauru",
    alpha2: "NR",
    alpha3: "NRU",
    numeric: "520",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Nauruan",
        native: "Dorerin Naoero",
        iso639_1: "na",
        bcp47: "na-NR",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-NR",
      },
    ],
  },
  {
    name: "Nepal",
    alpha2: "NP",
    alpha3: "NPL",
    numeric: "524",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      { dialect: "Nepali", native: "नेपाली", iso639_1: "ne", bcp47: "ne-NP" },
    ],
  },
  {
    name: "Netherlands",
    alpha2: "NL",
    alpha3: "NLD",
    numeric: "528",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Dutch",
        native: "Nederlands",
        iso639_1: "nl",
        bcp47: "nl-NL",
      },
    ],
  },
  {
    name: "New Caledonia",
    alpha2: "NC",
    alpha3: "NCL",
    numeric: "540",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-NC",
      },
    ],
  },
  {
    name: "New Zealand",
    alpha2: "NZ",
    alpha3: "NZL",
    numeric: "554",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-NZ",
      },
      {
        dialect: "Maori",
        native: "te reo Māori",
        iso639_1: "mi",
        bcp47: "mi-NZ",
      },
      {
        dialect: "New Zealand Sign Language",
        native: "New Zealand Sign Language",
        iso639_3: "nzs",
        bcp47: "nzs-NZ",
      }, // ISO 639-3
    ],
  },
  {
    name: "Nicaragua",
    alpha2: "NI",
    alpha3: "NIC",
    numeric: "558",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-NI",
      },
    ],
  },
  {
    name: "Niger",
    alpha2: "NE",
    alpha3: "NER",
    numeric: "562",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-NE",
      },
    ],
  },
  {
    name: "Nigeria",
    alpha2: "NG",
    alpha3: "NGA",
    numeric: "566",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-NG",
      },
      // Major regional languages like Hausa, Yoruba, Igbo also spoken.
    ],
  },
  {
    name: "Niue",
    alpha2: "NU",
    alpha3: "NIU",
    numeric: "570",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Niuean",
        native: "ko e Vagahau Niue",
        iso639_3: "niu",
        bcp47: "niu-NU",
      }, // ISO 639-3
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-NU",
      },
    ],
  },
  {
    name: "Norfolk Island",
    alpha2: "NF",
    alpha3: "NFK",
    numeric: "574",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-NF",
      },
      // Norfuk (nfk) - no 639-1
    ],
  },
  {
    name: "Republic of North Macedonia",
    alpha2: "MK",
    alpha3: "MKD",
    numeric: "807",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Macedonian",
        native: "македонски јазик",
        iso639_1: "mk",
        bcp47: "mk-MK",
      },
    ],
  },
  {
    name: "Northern Mariana Islands",
    alpha2: "MP",
    alpha3: "MNP",
    numeric: "580",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-MP",
      },
      {
        dialect: "Chamorro",
        native: "Finuʼ Chamoru",
        iso639_1: "ch",
        bcp47: "ch-MP",
      },
    ],
  },
  {
    name: "Norway",
    alpha2: "NO",
    alpha3: "NOR",
    numeric: "578",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Norwegian Bokmal",
        native: "norsk bokmål",
        iso639_1: "nb",
        bcp47: "nb-NO",
      },
      {
        dialect: "Norwegian Nynorsk",
        native: "nynorsk",
        iso639_1: "nn",
        bcp47: "nn-NO",
      },
      // Sami languages also recognized.
    ],
  },
  {
    name: "Oman",
    alpha2: "OM",
    alpha3: "OMN",
    numeric: "512",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-OM" },
    ],
  },
  {
    name: "Pakistan",
    alpha2: "PK",
    alpha3: "PAK",
    numeric: "586",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      { dialect: "Urdu", native: "اُردُو", iso639_1: "ur", bcp47: "ur-PK" },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-PK",
      },
    ],
  },
  {
    name: "Palau",
    alpha2: "PW",
    alpha3: "PLW",
    numeric: "585",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Palauan",
        native: "Tebil era Belau",
        iso639_3: "pau",
        bcp47: "pau-PW",
      }, // ISO 639-3
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-PW",
      },
    ],
  },
  {
    name: "Palestine, State of",
    alpha2: "PS",
    alpha3: "PSE",
    numeric: "275",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-PS" },
    ],
  },
  {
    name: "Panama",
    alpha2: "PA",
    alpha3: "PAN",
    numeric: "591",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-PA",
      },
    ],
  },
  {
    name: "Papua New Guinea",
    alpha2: "PG",
    alpha3: "PNG",
    numeric: "598",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Tok Pisin",
        native: "Tok Pisin",
        iso639_3: "tpi",
        bcp47: "tpi-PG",
      }, // ISO 639-3
      {
        dialect: "Hiri Motu",
        native: "Hiri Motu",
        iso639_1: "ho",
        bcp47: "ho-PG",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-PG",
      },
      // Over 800 indigenous languages
    ],
  },
  {
    name: "Paraguay",
    alpha2: "PY",
    alpha3: "PRY",
    numeric: "600",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-PY",
      },
      {
        dialect: "Guarani",
        native: "Avañe'ẽ",
        iso639_1: "gn",
        bcp47: "gn-PY",
      },
    ],
  },
  {
    name: "Peru",
    alpha2: "PE",
    alpha3: "PER",
    numeric: "604",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-PE",
      },
      {
        dialect: "Quechua",
        native: "Runa simi",
        iso639_1: "qu",
        bcp47: "qu-PE",
      },
    ],
  },
  {
    name: "Philippines",
    alpha2: "PH",
    alpha3: "PHL",
    numeric: "608",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Filipino",
        native: "Filipino",
        iso639_3: "fil",
        bcp47: "fil-PH",
      }, // ISO 639-3, but common for Tagalog
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-PH",
      },
    ],
  },
  {
    name: "Pitcairn",
    alpha2: "PN",
    alpha3: "PCN",
    numeric: "612",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-PN",
      },
      // Pitkern (pih) - no 639-1
    ],
  },
  {
    name: "Poland",
    alpha2: "PL",
    alpha3: "POL",
    numeric: "616",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Polish", native: "polski", iso639_1: "pl", bcp47: "pl-PL" },
    ],
  },
  {
    name: "Portugal",
    alpha2: "PT",
    alpha3: "PRT",
    numeric: "620",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Portuguese",
        native: "Português",
        iso639_1: "pt",
        bcp47: "pt-PT",
      },
    ],
  },
  {
    name: "Puerto Rico",
    alpha2: "PR",
    alpha3: "PRI",
    numeric: "630",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-PR",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-PR",
      },
    ],
  },
  {
    name: "Qatar",
    alpha2: "QA",
    alpha3: "QAT",
    numeric: "634",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-QA" },
    ],
  },
  {
    name: "Réunion",
    alpha2: "RE",
    alpha3: "REU",
    numeric: "638",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-RE",
      },
    ],
  },
  {
    name: "Romania",
    alpha2: "RO",
    alpha3: "ROU",
    numeric: "642",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Romanian",
        native: "română",
        iso639_1: "ro",
        bcp47: "ro-RO",
      },
    ],
  },
  {
    name: "Russian Federation",
    alpha2: "RU",
    alpha3: "RUS",
    numeric: "643",
    continents: ["Europe", "Asia"],
    regions: ["EMEA", "APAC"],
    dialects: [
      {
        dialect: "Russian",
        native: "русский язык",
        iso639_1: "ru",
        bcp47: "ru-RU",
      },
    ],
  },
  {
    name: "Rwanda",
    alpha2: "RW",
    alpha3: "RWA",
    numeric: "646",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Kinyarwanda",
        native: "Kinyarwanda",
        iso639_1: "rw",
        bcp47: "rw-RW",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-RW",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-RW",
      },
    ],
  },
  {
    name: "Saint Barthélemy",
    alpha2: "BL",
    alpha3: "BLM",
    numeric: "652",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-BL",
      },
    ],
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2: "SH",
    alpha3: "SHN",
    numeric: "654",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-SH",
      },
    ],
  },
  {
    name: "Saint Kitts and Nevis",
    alpha2: "KN",
    alpha3: "KNA",
    numeric: "659",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-KN",
      },
    ],
  },
  {
    name: "Saint Lucia",
    alpha2: "LC",
    alpha3: "LCA",
    numeric: "662",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-LC",
      },
    ],
  },
  {
    name: "Saint Martin (French part)",
    alpha2: "MF",
    alpha3: "MAF",
    numeric: "663",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-MF",
      },
    ],
  },
  {
    name: "Saint Pierre and Miquelon",
    alpha2: "PM",
    alpha3: "SPM",
    numeric: "666",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-PM",
      },
    ],
  },
  {
    name: "Saint Vincent and the Grenadines",
    alpha2: "VC",
    alpha3: "VCT",
    numeric: "670",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-VC",
      },
    ],
  },
  {
    name: "Samoa",
    alpha2: "WS",
    alpha3: "WSM",
    numeric: "882",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Samoan",
        native: "Gagana Sāmoa",
        iso639_1: "sm",
        bcp47: "sm-WS",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-WS",
      },
    ],
  },
  {
    name: "San Marino",
    alpha2: "SM",
    alpha3: "SMR",
    numeric: "674",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Italian",
        native: "Italiano",
        iso639_1: "it",
        bcp47: "it-SM",
      },
    ],
  },
  {
    name: "Sao Tome and Principe",
    alpha2: "ST",
    alpha3: "STP",
    numeric: "678",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Portuguese",
        native: "Português",
        iso639_1: "pt",
        bcp47: "pt-ST",
      },
    ],
  },
  {
    name: "Saudi Arabia",
    alpha2: "SA",
    alpha3: "SAU",
    numeric: "682",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-SA" },
    ],
  },
  {
    name: "Senegal",
    alpha2: "SN",
    alpha3: "SEN",
    numeric: "686",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-SN",
      },
    ],
  },
  {
    name: "Serbia",
    alpha2: "RS",
    alpha3: "SRB",
    numeric: "688",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Serbian",
        native: "српски језик",
        iso639_1: "sr",
        bcp47: "sr-RS",
      },
    ],
  },
  {
    name: "Seychelles",
    alpha2: "SC",
    alpha3: "SYC",
    numeric: "690",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Seychellois Creole",
        native: "Seselwa",
        iso639_3: "crs",
        bcp47: "crs-SC",
      }, // ISO 639-3
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-SC",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-SC",
      },
    ],
  },
  {
    name: "Sierra Leone",
    alpha2: "SL",
    alpha3: "SLE",
    numeric: "694",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-SL",
      },
      // Krio (kri) - no 639-1
    ],
  },
  {
    name: "Singapore",
    alpha2: "SG",
    alpha3: "SGP",
    numeric: "702",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-SG",
      },
      {
        dialect: "Malay",
        native: "Bahasa Melayu",
        iso639_1: "ms",
        bcp47: "ms-SG",
      },
      {
        dialect: "Chinese",
        native: "中文",
        iso639_1: "zh",
        bcp47: "zh-Hans-SG",
      }, // Simplified Chinese
      { dialect: "Tamil", native: "தமிழ்", iso639_1: "ta", bcp47: "ta-SG" },
    ],
  },
  {
    name: "Sint Maarten (Dutch part)",
    alpha2: "SX",
    alpha3: "SXM",
    numeric: "534",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "Dutch",
        native: "Nederlands",
        iso639_1: "nl",
        bcp47: "nl-SX",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-SX",
      },
    ],
  },
  {
    name: "Slovakia",
    alpha2: "SK",
    alpha3: "SVK",
    numeric: "703",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Slovak",
        native: "slovenčina",
        iso639_1: "sk",
        bcp47: "sk-SK",
      },
    ],
  },
  {
    name: "Slovenia",
    alpha2: "SI",
    alpha3: "SVN",
    numeric: "705",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Slovenian",
        native: "slovenski jezik",
        iso639_1: "sl",
        bcp47: "sl-SI",
      },
    ],
  },
  {
    name: "Solomon Islands",
    alpha2: "SB",
    alpha3: "SLB",
    numeric: "090",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-SB",
      },
      // Pijin (pis) - no 639-1
    ],
  },
  {
    name: "Somalia",
    alpha2: "SO",
    alpha3: "SOM",
    numeric: "706",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Somali",
        native: "Af Soomaali",
        iso639_1: "so",
        bcp47: "so-SO",
      },
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-SO" },
    ],
  },
  {
    name: "South Africa",
    alpha2: "ZA",
    alpha3: "ZAF",
    numeric: "710",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Afrikaans",
        native: "Afrikaans",
        iso639_1: "af",
        bcp47: "af-ZA",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-ZA",
      },
      { dialect: "Zulu", native: "isiZulu", iso639_1: "zu", bcp47: "zu-ZA" },
      { dialect: "Xhosa", native: "isiXhosa", iso639_1: "xh", bcp47: "xh-ZA" },
      {
        dialect: "Southern Sotho",
        native: "Sesotho",
        iso639_1: "st",
        bcp47: "st-ZA",
      },
      {
        dialect: "Tswana",
        native: "Setswana",
        iso639_1: "tn",
        bcp47: "tn-ZA",
      },
      { dialect: "Swati", native: "SiSwati", iso639_1: "ss", bcp47: "ss-ZA" },
      {
        dialect: "Venda",
        native: "Tshivenḓa",
        iso639_1: "ve",
        bcp47: "ve-ZA",
      },
      {
        dialect: "Tsonga",
        native: "Xitsonga",
        iso639_1: "ts",
        bcp47: "ts-ZA",
      },
      {
        dialect: "Northern Sotho",
        native: "Sesotho sa Leboa",
        iso639_3: "nso",
        bcp47: "nso-ZA",
      }, // ISO 639-3
      {
        dialect: "Ndebele",
        native: "isiNdebele",
        iso639_1: "nr",
        bcp47: "nr-ZA",
      }, // ISO 639-3
    ],
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    alpha2: "GS",
    alpha3: "SGS",
    numeric: "239",
    continents: ["Antarctica"],
    regions: [],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-GS",
      },
    ],
  },
  {
    name: "South Sudan",
    alpha2: "SS",
    alpha3: "SSD",
    numeric: "728",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-SS",
      },
    ],
  },
  {
    name: "Spain",
    alpha2: "ES",
    alpha3: "ESP",
    numeric: "724",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-ES",
      },
      { dialect: "Catalan", native: "Català", iso639_1: "ca", bcp47: "ca-ES" },
      {
        dialect: "Galician",
        native: "Galego",
        iso639_1: "gl",
        bcp47: "gl-ES",
      },
      { dialect: "Basque", native: "Euskara", iso639_1: "eu", bcp47: "eu-ES" },
      // Aranese, Valencian, etc. are also recognized in specific regions
    ],
  },
  {
    name: "Sri Lanka",
    alpha2: "LK",
    alpha3: "LKA",
    numeric: "144",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      { dialect: "Sinhala", native: "සිංහල", iso639_1: "si", bcp47: "si-LK" },
      { dialect: "Tamil", native: "தமிழ்", iso639_1: "ta", bcp47: "ta-LK" },
    ],
  },
  {
    name: "Sudan",
    alpha2: "SD",
    alpha3: "SDN",
    numeric: "729",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-SD" },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-SD",
      },
    ],
  },
  {
    name: "Suriname",
    alpha2: "SR",
    alpha3: "SUR",
    numeric: "740",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Dutch",
        native: "Nederlands",
        iso639_1: "nl",
        bcp47: "nl-SR",
      },
    ],
  },
  {
    name: "Svalbard and Jan Mayen",
    alpha2: "SJ",
    alpha3: "SJM",
    numeric: "744",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Norwegian",
        native: "Norsk",
        iso639_1: "no",
        bcp47: "no-SJ",
      },
    ],
  },
  {
    name: "Sweden",
    alpha2: "SE",
    alpha3: "SWE",
    numeric: "752",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Swedish",
        native: "Svenska",
        iso639_1: "sv",
        bcp47: "sv-SE",
      },
    ],
  },
  {
    name: "Switzerland",
    alpha2: "CH",
    alpha3: "CHE",
    numeric: "756",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "German", native: "Deutsch", iso639_1: "de", bcp47: "de-CH" },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-CH",
      },
      {
        dialect: "Italian",
        native: "Italiano",
        iso639_1: "it",
        bcp47: "it-CH",
      },
      {
        dialect: "Romansh",
        native: "rumantsch",
        iso639_1: "rm",
        bcp47: "rm-CH",
      },
    ],
  },
  {
    name: "Syrian Arab Republic",
    alpha2: "SY",
    alpha3: "SYR",
    numeric: "760",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-SY" },
    ],
  },
  {
    name: "Taiwan (Province of China)",
    alpha2: "TW",
    alpha3: "TWN",
    numeric: "158",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Chinese",
        native: "中文",
        iso639_1: "zh",
        bcp47: "zh-Hant-TW",
      }, // Traditional Chinese for Taiwan
    ],
  },
  {
    name: "Tajikistan",
    alpha2: "TJ",
    alpha3: "TJK",
    numeric: "762",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      { dialect: "Tajik", native: "тоҷикӣ", iso639_1: "tg", bcp47: "tg-TJ" },
      {
        dialect: "Russian",
        native: "русский язык",
        iso639_1: "ru",
        bcp47: "ru-TJ",
      },
    ],
  },
  {
    name: "Tanzania, United Republic of",
    alpha2: "TZ",
    alpha3: "TZA",
    numeric: "834",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "Swahili",
        native: "Kiswahili",
        iso639_1: "sw",
        bcp47: "sw-TZ",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-TZ",
      },
    ],
  },
  {
    name: "Thailand",
    alpha2: "TH",
    alpha3: "THA",
    numeric: "764",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      { dialect: "Thai", native: "ไทย", iso639_1: "th", bcp47: "th-TH" },
    ],
  },
  {
    name: "Timor-Leste",
    alpha2: "TL",
    alpha3: "TLS",
    numeric: "626",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      { dialect: "Tetum", native: "Tetun", iso639_3: "tet", bcp47: "tet-TL" }, // ISO 639-3
      {
        dialect: "Portuguese",
        native: "Português",
        iso639_1: "pt",
        bcp47: "pt-TL",
      },
    ],
  },
  {
    name: "Togo",
    alpha2: "TG",
    alpha3: "TGO",
    numeric: "768",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-TG",
      },
    ],
  },
  {
    name: "Tokelau",
    alpha2: "TK",
    alpha3: "TKL",
    numeric: "772",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Tokelauan",
        native: "Gagana Tokelau",
        iso639_3: "tkl",
        bcp47: "tkl-TK",
      }, // ISO 639-3
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-TK",
      },
    ],
  },
  {
    name: "Tonga",
    alpha2: "TO",
    alpha3: "TON",
    numeric: "776",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Tongan",
        native: "lea faka-Tonga",
        iso639_1: "to",
        bcp47: "to-TO",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-TO",
      },
    ],
  },
  {
    name: "Trinidad and Tobago",
    alpha2: "TT",
    alpha3: "TTO",
    numeric: "780",
    continents: ["South America", "Africa"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-TT",
      },
    ],
  },
  {
    name: "Tunisia",
    alpha2: "TN",
    alpha3: "TUN",
    numeric: "788",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-TN" },
    ],
  },
  {
    name: "Turkey",
    alpha2: "TR",
    alpha3: "TUR",
    numeric: "792",
    continents: ["Asia", "Europe"],
    regions: ["EMEA"],
    dialects: [
      { dialect: "Turkish", native: "Türkçe", iso639_1: "tr", bcp47: "tr-TR" },
    ],
  },
  {
    name: "Turkmenistan",
    alpha2: "TM",
    alpha3: "TKM",
    numeric: "795",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Turkmen",
        native: "Türkmen dili",
        iso639_1: "tk",
        bcp47: "tk-TM",
      },
      {
        dialect: "Russian",
        native: "русский язык",
        iso639_1: "ru",
        bcp47: "ru-TM",
      },
    ],
  },
  {
    name: "Turks and Caicos Islands",
    alpha2: "TC",
    alpha3: "TCA",
    numeric: "796",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-TC",
      },
    ],
  },
  {
    name: "Tuvalu",
    alpha2: "TV",
    alpha3: "TUV",
    numeric: "798",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Tuvaluan",
        native: "Te Gagana Tuvalu",
        iso639_3: "tvl",
        bcp47: "tvl-TV",
      }, // ISO 639-3
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-TV",
      },
    ],
  },
  {
    name: "Uganda",
    alpha2: "UG",
    alpha3: "UGA",
    numeric: "800",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-UG",
      },
      {
        dialect: "Luganda",
        native: "Luganda",
        iso639_1: "lg",
        bcp47: "lg-UG",
      },
      {
        dialect: "Swahili",
        native: "Kiswahili",
        iso639_1: "sw",
        bcp47: "sw-UG",
      },
    ],
  },
  {
    name: "Ukraine",
    alpha2: "UA",
    alpha3: "UKR",
    numeric: "804",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Ukrainian",
        native: "українська",
        iso639_1: "uk",
        bcp47: "uk-UA",
      },
    ],
  },
  {
    name: "United Arab Emirates",
    alpha2: "AE",
    alpha3: "ARE",
    numeric: "784",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-AE" },
    ],
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    alpha2: "GB",
    alpha3: "GBR",
    numeric: "826",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-GB",
      },
      {
        dialect: "Scottish Gaelic",
        native: "Gàidhlig",
        iso639_1: "gd",
        bcp47: "gd-GB",
      },
      { dialect: "Welsh", native: "Cymraeg", iso639_1: "cy", bcp47: "cy-GB" },
      { dialect: "Irish", native: "Gaeilge", iso639_1: "ga", bcp47: "ga-GB" }, // Recognized in Northern Ireland
      {
        dialect: "Cornish",
        native: "Kernowek",
        iso639_1: "kw",
        bcp47: "kw-GB",
      },
      { dialect: "Scots", native: "Scots", iso639_3: "sco", bcp47: "sco-GB" }, // ISO 639-3
    ],
  },
  {
    name: "United States Minor Outlying Islands",
    alpha2: "UM",
    alpha3: "UMI",
    numeric: "581",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-UM",
      },
    ],
  },
  {
    name: "United States of America",
    alpha2: "US",
    alpha3: "USA",
    numeric: "840",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-US",
      },
    ],
  },
  {
    name: "Uruguay",
    alpha2: "UY",
    alpha3: "URY",
    numeric: "858",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-UY",
      },
    ],
  },
  {
    name: "Uzbekistan",
    alpha2: "UZ",
    alpha3: "UZB",
    numeric: "860",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Uzbek",
        native: "Oʻzbek tili",
        iso639_1: "uz",
        bcp47: "uz-UZ",
      },
      {
        dialect: "Russian",
        native: "русский язык",
        iso639_1: "ru",
        bcp47: "ru-UZ",
      },
    ],
  },
  {
    name: "Vanuatu",
    alpha2: "VU",
    alpha3: "VUT",
    numeric: "548",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Bislama",
        native: "Bislama",
        iso639_1: "bi",
        bcp47: "bi-VU",
      },
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-VU",
      },
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-VU",
      },
    ],
  },
  {
    name: "Bolivarian Republic of Venezuela",
    alpha2: "VE",
    alpha3: "VEN",
    numeric: "862",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-VE",
      },
    ],
  },
  {
    name: "Vietnam",
    alpha2: "VN",
    alpha3: "VNM",
    numeric: "704",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "Vietnamese",
        native: "Tiếng Việt",
        iso639_1: "vi",
        bcp47: "vi-VN",
      },
    ],
  },
  {
    name: "Virgin Islands (British)",
    alpha2: "VG",
    alpha3: "VGB",
    numeric: "092",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-VG",
      },
    ],
  },
  {
    name: "Virgin Islands (U.S.)",
    alpha2: "VI",
    alpha3: "VIR",
    numeric: "850",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-VI",
      },
    ],
  },
  {
    name: "Wallis and Futuna",
    alpha2: "WF",
    alpha3: "WLF",
    numeric: "876",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      {
        dialect: "French",
        native: "Français",
        iso639_1: "fr",
        bcp47: "fr-WF",
      },
      // Wallisian (wls) and Futunan (fud) - no 639-1
    ],
  },
  {
    name: "Western Sahara",
    alpha2: "EH",
    alpha3: "ESH",
    numeric: "732",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-EH" },
      {
        dialect: "Spanish",
        native: "Español",
        iso639_1: "es",
        bcp47: "es-EH",
      }, // Historically recognized
    ],
  },
  {
    name: "Yemen",
    alpha2: "YE",
    alpha3: "YEM",
    numeric: "887",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: [
      { dialect: "Arabic", native: "العربية", iso639_1: "ar", bcp47: "ar-YE" },
    ],
  },
  {
    name: "Zambia",
    alpha2: "ZM",
    alpha3: "ZMB",
    numeric: "894",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-ZM",
      },
    ],
  },
  {
    name: "Zimbabwe",
    alpha2: "ZW",
    alpha3: "ZWE",
    numeric: "716",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      {
        dialect: "English",
        native: "English",
        iso639_1: "en",
        bcp47: "en-ZW",
      },
      { dialect: "Shona", native: "chiShona", iso639_1: "sn", bcp47: "sn-ZW" },
      {
        dialect: "Northern Ndebele",
        native: "isiNdebele",
        iso639_1: "nd",
        bcp47: "nd-ZW",
      },
      // Other languages also official, but including the most common for brevity
    ],
  },
  {
    name: "Åland Islands",
    alpha2: "AX",
    alpha3: "ALA",
    numeric: "248",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      {
        dialect: "Swedish",
        native: "Svenska",
        iso639_1: "sv",
        bcp47: "sv-AX",
      },
    ],
  },
];

export const continents: Array<Continent> = [
  "Africa",
  "Antarctica",
  "Asia",
  "Europe",
  "North America",
  "Oceania",
  "South America",
];

export const regions: Array<Region> = [
  "EMEA",
  "APAC",
  "AMER",
  "LATAM",
  "NA",
  "SA",
  "MEA",
];
