import type { Continent, ISO3166, Region } from "./types";

export const countries: Array<ISO3166> = [
  {
    name: "Afghanistan",
    alpha2: "AF",
    alpha3: "AFG",
    numeric: "004",
    continents: ["Asia"],
    regions: ["APAC", "MEA"],
    dialects: ["fa-AF", "ps-AF"],
  },
  {
    name: "Albania",
    alpha2: "AL",
    alpha3: "ALB",
    numeric: "008",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["sq-AL"],
  },
  {
    name: "Algeria",
    alpha2: "DZ",
    alpha3: "DZA",
    numeric: "012",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      "ar-DZ",
      // While Berber is widely spoken, "Berber" is a language family.
      // For more specific dialect, a different ISO code might be needed or a broader BCP47 tag.
      // Leaving it out for now to adhere strictly to singular languages with iso639_1 codes.
    ],
  },
  {
    name: "American Samoa",
    alpha2: "AS",
    alpha3: "ASM",
    numeric: "016",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["en-AS", "sm-AS"],
  },
  {
    name: "Andorra",
    alpha2: "AD",
    alpha3: "AND",
    numeric: "020",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["ca-AD"],
  },
  {
    name: "Angola",
    alpha2: "AO",
    alpha3: "AGO",
    numeric: "024",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["pt-AO"],
  },
  {
    name: "Anguilla",
    alpha2: "AI",
    alpha3: "AIA",
    numeric: "660",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-AI"],
  },
  {
    name: "Antarctica",
    alpha2: "AQ",
    alpha3: "ATA",
    numeric: "010",
    continents: ["Antarctica"],
    regions: [],
    dialects: ["en-AQ", "es-AQ", "fr-AQ", "ru-AQ"],
  },
  {
    name: "Antigua and Barbuda",
    alpha2: "AG",
    alpha3: "ATG",
    numeric: "028",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-AG"],
  },
  {
    name: "Argentina",
    alpha2: "AR",
    alpha3: "ARG",
    numeric: "032",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["es-AR"],
  },
  {
    name: "Armenia",
    alpha2: "AM",
    alpha3: "ARM",
    numeric: "051",
    continents: ["Asia", "Europe"],
    regions: ["EMEA", "APAC"],
    dialects: ["hy-AM"],
  },
  {
    name: "Aruba",
    alpha2: "AW",
    alpha3: "ABW",
    numeric: "533",
    continents: ["South America", "Europe"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["nl-AW", "pap-AW"],
  },
  {
    name: "Australia",
    alpha2: "AU",
    alpha3: "AUS",
    numeric: "036",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["en-AU"],
  },
  {
    name: "Austria",
    alpha2: "AT",
    alpha3: "AUT",
    numeric: "040",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["de-AT"],
  },
  {
    name: "Azerbaijan",
    alpha2: "AZ",
    alpha3: "AZE",
    numeric: "031",
    continents: ["Asia", "Europe"],
    regions: ["EMEA", "APAC"],
    dialects: ["az-AZ"],
  },
  {
    name: "Bahamas",
    alpha2: "BS",
    alpha3: "BHS",
    numeric: "044",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-BS"],
  },
  {
    name: "Bahrain",
    alpha2: "BH",
    alpha3: "BHR",
    numeric: "048",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-BH"],
  },
  {
    name: "Bangladesh",
    alpha2: "BD",
    alpha3: "BGD",
    numeric: "050",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["bn-BD"],
  },
  {
    name: "Barbados",
    alpha2: "BB",
    alpha3: "BRB",
    numeric: "052",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-BB"],
  },
  {
    name: "Belarus",
    alpha2: "BY",
    alpha3: "BLR",
    numeric: "112",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["be-BY", "ru-BY"],
  },
  {
    name: "Belgium",
    alpha2: "BE",
    alpha3: "BEL",
    numeric: "056",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["nl-BE", "fr-BE", "de-BE"],
  },
  {
    name: "Belize",
    alpha2: "BZ",
    alpha3: "BLZ",
    numeric: "084",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-BZ"],
  },
  {
    name: "Benin",
    alpha2: "BJ",
    alpha3: "BEN",
    numeric: "204",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-BJ"],
  },
  {
    name: "Bermuda",
    alpha2: "BM",
    alpha3: "BMU",
    numeric: "060",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: ["en-BM"],
  },
  {
    name: "Bhutan",
    alpha2: "BT",
    alpha3: "BTN",
    numeric: "064",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["dz-BT"],
  },
  {
    name: "Plurinational State of Bolivia",
    alpha2: "BO",
    alpha3: "BOL",
    numeric: "068",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: [
      "es-BO",
      "ay-BO",
      "gn-BO",
      // Bolivia has 37 official languages, adding major ones.
    ],
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    alpha2: "BQ",
    alpha3: "BES",
    numeric: "535",
    continents: ["South America", "Europe"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["nl-BQ", "en-BQ"],
  },
  {
    name: "Bosnia and Herzegovina",
    alpha2: "BA",
    alpha3: "BIH",
    numeric: "070",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["bs-BA", "hr-BA", "sr-BA"],
  },
  {
    name: "Botswana",
    alpha2: "BW",
    alpha3: "BWA",
    numeric: "072",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-BW", "tn-BW"],
  },
  {
    name: "Bouvet Island",
    alpha2: "BV",
    alpha3: "BVT",
    numeric: "074",
    continents: ["Antarctica"],
    regions: [],
    dialects: ["en-BV"],
  },
  {
    name: "Brazil",
    alpha2: "BR",
    alpha3: "BRA",
    numeric: "076",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["pt-BR"],
  },
  {
    name: "British Indian Ocean Territory",
    alpha2: "IO",
    alpha3: "IOT",
    numeric: "086",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["en-IO"],
  },
  {
    name: "Brunei Darussalam",
    alpha2: "BN",
    alpha3: "BRN",
    numeric: "096",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["ms-BN"],
  },
  {
    name: "Bulgaria",
    alpha2: "BG",
    alpha3: "BGR",
    numeric: "100",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["bg-BG"],
  },
  {
    name: "Burkina Faso",
    alpha2: "BF",
    alpha3: "BFA",
    numeric: "854",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-BF"],
  },
  {
    name: "Burundi",
    alpha2: "BI",
    alpha3: "BDI",
    numeric: "108",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["rn-BI", "fr-BI", "en-BI"],
  },
  {
    name: "Cape Verde",
    alpha2: "CV",
    alpha3: "CPV",
    numeric: "132",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["pt-CV"],
  },
  {
    name: "Cambodia",
    alpha2: "KH",
    alpha3: "KHM",
    numeric: "116",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["km-KH"],
  },
  {
    name: "Cameroon",
    alpha2: "CM",
    alpha3: "CMR",
    numeric: "120",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-CM", "fr-CM"],
  },
  {
    name: "Canada",
    alpha2: "CA",
    alpha3: "CAN",
    numeric: "124",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: ["en-CA", "fr-CA"],
  },
  {
    name: "Cayman Islands",
    alpha2: "KY",
    alpha3: "CYM",
    numeric: "136",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-KY"],
  },
  {
    name: "Central African Republic",
    alpha2: "CF",
    alpha3: "CAF",
    numeric: "140",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-CF", "sg-CF"],
  },
  {
    name: "Chad",
    alpha2: "TD",
    alpha3: "TCD",
    numeric: "148",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-TD", "fr-TD"],
  },
  {
    name: "Chile",
    alpha2: "CL",
    alpha3: "CHL",
    numeric: "152",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["es-CL"],
  },
  {
    name: "China",
    alpha2: "CN",
    alpha3: "CHN",
    numeric: "156",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["zh-Hans-CN"],
  },
  {
    name: "Christmas Island",
    alpha2: "CX",
    alpha3: "CXR",
    numeric: "162",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["en-CX"],
  },
  {
    name: "Cocos (Keeling) Islands",
    alpha2: "CC",
    alpha3: "CCK",
    numeric: "166",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["en-CC"],
  },
  {
    name: "Colombia",
    alpha2: "CO",
    alpha3: "COL",
    numeric: "170",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["es-CO"],
  },
  {
    name: "Comoros",
    alpha2: "KM",
    alpha3: "COM",
    numeric: "174",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-KM", "fr-KM"],
  },
  {
    name: "Congo", // Republic of the Congo
    alpha2: "CG",
    alpha3: "COG",
    numeric: "178",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-CG", "ln-CG", "kg-CG"],
  },
  {
    name: "Democratic Republic of Congo",
    alpha2: "CD",
    alpha3: "COD",
    numeric: "180",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-CD", "ln-CD", "kg-CD", "sw-CD", "lu-CD"],
  },
  {
    name: "Cook Islands",
    alpha2: "CK",
    alpha3: "COK",
    numeric: "184",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["en-CK"],
  },
  {
    name: "Costa Rica",
    alpha2: "CR",
    alpha3: "CRI",
    numeric: "188",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["es-CR"],
  },
  {
    name: "Côte d'Ivoire",
    alpha2: "CI",
    alpha3: "CIV",
    numeric: "384",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-CI"],
  },
  {
    name: "Croatia",
    alpha2: "HR",
    alpha3: "HRV",
    numeric: "191",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["hr-HR"],
  },
  {
    name: "Cuba",
    alpha2: "CU",
    alpha3: "CUB",
    numeric: "192",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["es-CU"],
  },
  {
    name: "Curaçao",
    alpha2: "CW",
    alpha3: "CUW",
    numeric: "531",
    continents: ["South America", "Europe"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["nl-CW", "en-CW"],
  },
  {
    name: "Cyprus",
    alpha2: "CY",
    alpha3: "CYP",
    numeric: "196",
    continents: ["Europe", "Asia"],
    regions: ["EMEA"],
    dialects: ["el-CY", "tr-CY"],
  },
  {
    name: "Czechia",
    alpha2: "CZ",
    alpha3: "CZE",
    numeric: "203",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["cs-CZ"],
  },
  {
    name: "Denmark",
    alpha2: "DK",
    alpha3: "DNK",
    numeric: "208",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["da-DK"],
  },
  {
    name: "Djibouti",
    alpha2: "DJ",
    alpha3: "DJI",
    numeric: "262",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-DJ", "fr-DJ", "so-DJ", "aa-DJ"],
  },
  {
    name: "Dominica",
    alpha2: "DM",
    alpha3: "DMA",
    numeric: "212",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-DM"],
  },
  {
    name: "Dominican Republic",
    alpha2: "DO",
    alpha3: "DOM",
    numeric: "214",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["es-DO"],
  },
  {
    name: "Ecuador",
    alpha2: "EC",
    alpha3: "ECU",
    numeric: "218",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["es-EC", "qu-EC"],
  },
  {
    name: "Egypt",
    alpha2: "EG",
    alpha3: "EGY",
    numeric: "818",
    continents: ["Africa", "Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-EG"],
  },
  {
    name: "El Salvador",
    alpha2: "SV",
    alpha3: "SLV",
    numeric: "222",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["es-SV"],
  },
  {
    name: "Equatorial Guinea",
    alpha2: "GQ",
    alpha3: "GNQ",
    numeric: "226",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["es-GQ", "fr-GQ", "pt-GQ"],
  },
  {
    name: "Eritrea",
    alpha2: "ER",
    alpha3: "ERI",
    numeric: "232",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["ti-ER", "ar-ER", "en-ER"],
  },
  {
    name: "Estonia",
    alpha2: "EE",
    alpha3: "EST",
    numeric: "233",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["et-EE"],
  },
  {
    name: "Eswatini",
    alpha2: "SZ",
    alpha3: "SWZ",
    numeric: "748",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-SZ", "ss-SZ"],
  },
  {
    name: "Ethiopia",
    alpha2: "ET",
    alpha3: "ETH",
    numeric: "231",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["am-ET", "om-ET", "ti-ET"],
  },
  {
    name: "Falkland Islands",
    alpha2: "FK",
    alpha3: "FLK",
    numeric: "238",
    continents: ["South America"],
    regions: ["AMER", "SA"],
    dialects: ["en-FK"],
  },
  {
    name: "Faroe Islands",
    alpha2: "FO",
    alpha3: "FRO",
    numeric: "234",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["fo-FO", "da-FO"],
  },
  {
    name: "Fiji",
    alpha2: "FJ",
    alpha3: "FJI",
    numeric: "242",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["en-FJ", "fj-FJ"],
  },
  {
    name: "Finland",
    alpha2: "FI",
    alpha3: "FIN",
    numeric: "246",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["fi-FI", "sv-FI"],
  },
  {
    name: "France",
    alpha2: "FR",
    alpha3: "FRA",
    numeric: "250",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["fr-FR"],
  },
  {
    name: "French Guiana",
    alpha2: "GF",
    alpha3: "GUF",
    numeric: "254",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["fr-GF"],
  },
  {
    name: "French Polynesia",
    alpha2: "PF",
    alpha3: "PYF",
    numeric: "258",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["fr-PF", "ty-PF"],
  },
  {
    name: "French Southern Territories",
    alpha2: "TF",
    alpha3: "ATF",
    numeric: "260",
    continents: ["Antarctica"],
    regions: [],
    dialects: ["fr-TF"],
  },
  {
    name: "Gabon",
    alpha2: "GA",
    alpha3: "GAB",
    numeric: "266",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-GA"],
  },
  {
    name: "Gambia",
    alpha2: "GM",
    alpha3: "GMB",
    numeric: "270",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-GM"],
  },
  {
    name: "Georgia",
    alpha2: "GE",
    alpha3: "GEO",
    numeric: "268",
    continents: ["Asia", "Europe"],
    regions: ["EMEA"],
    dialects: ["ka-GE"],
  },
  {
    name: "Germany",
    alpha2: "DE",
    alpha3: "DEU",
    numeric: "276",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["de-DE"],
  },
  {
    name: "Ghana",
    alpha2: "GH",
    alpha3: "GHA",
    numeric: "288",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-GH"],
  },
  {
    name: "Gibraltar",
    alpha2: "GI",
    alpha3: "GIB",
    numeric: "292",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["en-GI"],
  },
  {
    name: "Greece",
    alpha2: "GR",
    alpha3: "GRC",
    numeric: "300",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["el-GR"],
  },
  {
    name: "Greenland",
    alpha2: "GL",
    alpha3: "GRL",
    numeric: "304",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: ["kl-GL", "da-GL"],
  },
  {
    name: "Grenada",
    alpha2: "GD",
    alpha3: "GRD",
    numeric: "308",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-GD"],
  },
  {
    name: "Guadeloupe",
    alpha2: "GP",
    alpha3: "GLP",
    numeric: "312",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["fr-GP"],
  },
  {
    name: "Guam",
    alpha2: "GU",
    alpha3: "GUM",
    numeric: "316",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["en-GU", "ch-GU"],
  },
  {
    name: "Guatemala",
    alpha2: "GT",
    alpha3: "GTM",
    numeric: "320",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["es-GT"],
  },
  {
    name: "Guernsey",
    alpha2: "GG",
    alpha3: "GGY",
    numeric: "831",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["en-GG", "fr-GG"],
  },
  {
    name: "Guinea",
    alpha2: "GN",
    alpha3: "GIN",
    numeric: "324",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-GN"],
  },
  {
    name: "Guinea-Bissau",
    alpha2: "GW",
    alpha3: "GNB",
    numeric: "624",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["pt-GW"],
  },
  {
    name: "Guyana",
    alpha2: "GY",
    alpha3: "GUY",
    numeric: "328",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["en-GY"],
  },
  {
    name: "Haiti",
    alpha2: "HT",
    alpha3: "HTI",
    numeric: "332",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["ht-HT", "fr-HT"],
  },
  {
    name: "Heard Island and McDonald Islands",
    alpha2: "HM",
    alpha3: "HMD",
    numeric: "334",
    continents: ["Antarctica"],
    regions: [],
    dialects: ["en-HM"],
  },
  {
    name: "Holy See",
    alpha2: "VA",
    alpha3: "VAT",
    numeric: "336",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["la-VA", "it-VA"],
  },
  {
    name: "Honduras",
    alpha2: "HN",
    alpha3: "HND",
    numeric: "340",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["es-HN"],
  },
  {
    name: "Hong Kong",
    alpha2: "HK",
    alpha3: "HKG",
    numeric: "344",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["zh-Hant-HK", "en-HK"],
  },
  {
    name: "Hungary",
    alpha2: "HU",
    alpha3: "HUN",
    numeric: "348",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["hu-HU"],
  },
  {
    name: "Iceland",
    alpha2: "IS",
    alpha3: "ISL",
    numeric: "352",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["is-IS"],
  },
  {
    name: "India",
    alpha2: "IN",
    alpha3: "IND",
    numeric: "356",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: [
      "hi-IN",
      "en-IN",
      // India has many official languages, including Bengali, Marathi, Telugu, Tamil, Gujarati, etc.
      // For brevity, only the two federal official languages are included.
    ],
  },
  {
    name: "Indonesia",
    alpha2: "ID",
    alpha3: "IDN",
    numeric: "360",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["id-ID"],
  },
  {
    name: "Iran (Islamic Republic of)",
    alpha2: "IR",
    alpha3: "IRN",
    numeric: "364",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["fa-IR"],
  },
  {
    name: "Iraq",
    alpha2: "IQ",
    alpha3: "IRQ",
    numeric: "368",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-IQ", "ku-IQ"],
  },
  {
    name: "Ireland",
    alpha2: "IE",
    alpha3: "IRL",
    numeric: "372",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["ga-IE", "en-IE"],
  },
  {
    name: "Isle of Man",
    alpha2: "IM",
    alpha3: "IMN",
    numeric: "833",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["en-IM", "gv-IM"],
  },
  {
    name: "Israel",
    alpha2: "IL",
    alpha3: "ISR",
    numeric: "376",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["he-IL", "ar-IL"],
  },
  {
    name: "Italy",
    alpha2: "IT",
    alpha3: "ITA",
    numeric: "380",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["it-IT"],
  },
  {
    name: "Jamaica",
    alpha2: "JM",
    alpha3: "JAM",
    numeric: "388",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-JM"],
  },
  {
    name: "Japan",
    alpha2: "JP",
    alpha3: "JPN",
    numeric: "392",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["ja-JP"],
  },
  {
    name: "Jersey",
    alpha2: "JE",
    alpha3: "JEY",
    numeric: "832",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["en-JE", "fr-JE"],
  },
  {
    name: "Jordan",
    alpha2: "JO",
    alpha3: "JOR",
    numeric: "400",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-JO"],
  },
  {
    name: "Kazakhstan",
    alpha2: "KZ",
    alpha3: "KAZ",
    numeric: "398",
    continents: ["Asia", "Europe"],
    regions: ["EMEA", "APAC"],
    dialects: ["kk-KZ", "ru-KZ"],
  },
  {
    name: "Kenya",
    alpha2: "KE",
    alpha3: "KEN",
    numeric: "404",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["sw-KE", "en-KE"],
  },
  {
    name: "Kiribati",
    alpha2: "KI",
    alpha3: "KIR",
    numeric: "296",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      "en-KI",
      "gil-KI", // ISO 639-3, no 639-1
    ],
  },
  {
    name: "Democratic People's Republic of Korea",
    alpha2: "KP",
    alpha3: "PRK",
    numeric: "408",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["ko-KP"],
  },
  {
    name: "Republic of Korea",
    alpha2: "KR",
    alpha3: "KOR",
    numeric: "410",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["ko-KR"],
  },
  {
    name: "Kuwait",
    alpha2: "KW",
    alpha3: "KWT",
    numeric: "414",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-KW"],
  },
  {
    name: "Kyrgyzstan",
    alpha2: "KG",
    alpha3: "KGZ",
    numeric: "417",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["ky-KG", "ru-KG"],
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2: "LA",
    alpha3: "LAO",
    numeric: "418",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["lo-LA"],
  },
  {
    name: "Latvia",
    alpha2: "LV",
    alpha3: "LVA",
    numeric: "428",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["lv-LV"],
  },
  {
    name: "Lebanon",
    alpha2: "LB",
    alpha3: "LBN",
    numeric: "422",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-LB", "fr-LB"],
  },
  {
    name: "Lesotho",
    alpha2: "LS",
    alpha3: "LSO",
    numeric: "426",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["st-LS", "en-LS"],
  },
  {
    name: "Liberia",
    alpha2: "LR",
    alpha3: "LBR",
    numeric: "430",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-LR"],
  },
  {
    name: "Libya",
    alpha2: "LY",
    alpha3: "LBY",
    numeric: "434",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-LY"],
  },
  {
    name: "Liechtenstein",
    alpha2: "LI",
    alpha3: "LIE",
    numeric: "438",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["de-LI"],
  },
  {
    name: "Lithuania",
    alpha2: "LT",
    alpha3: "LTU",
    numeric: "440",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["lt-LT"],
  },
  {
    name: "Luxembourg",
    alpha2: "LU",
    alpha3: "LUX",
    numeric: "442",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["lb-LU", "fr-LU", "de-LU"],
  },
  {
    name: "Macao",
    alpha2: "MO",
    alpha3: "MAC",
    numeric: "446",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["zh-Hant-MO", "pt-MO"],
  },
  {
    name: "Madagascar",
    alpha2: "MG",
    alpha3: "MDG",
    numeric: "450",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["mg-MG", "fr-MG"],
  },
  {
    name: "Malawi",
    alpha2: "MW",
    alpha3: "MWI",
    numeric: "454",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-MW", "ny-MW"],
  },
  {
    name: "Malaysia",
    alpha2: "MY",
    alpha3: "MYS",
    numeric: "458",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["ms-MY", "en-MY", "zh-Hans-MY", "ta-MY"],
  },
  {
    name: "Maldives",
    alpha2: "MV",
    alpha3: "MDV",
    numeric: "462",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["dv-MV"],
  },
  {
    name: "Mali",
    alpha2: "ML",
    alpha3: "MLI",
    numeric: "466",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-ML"],
  },
  {
    name: "Malta",
    alpha2: "MT",
    alpha3: "MLT",
    numeric: "470",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["mt-MT", "en-MT"],
  },
  {
    name: "Marshall Islands",
    alpha2: "MH",
    alpha3: "MHL",
    numeric: "584",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["mh-MH", "en-MH"],
  },
  {
    name: "Martinique",
    alpha2: "MQ",
    alpha3: "MTQ",
    numeric: "474",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["fr-MQ"],
  },
  {
    name: "Mauritania",
    alpha2: "MR",
    alpha3: "MRT",
    numeric: "478",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-MR"],
  },
  {
    name: "Mauritius",
    alpha2: "MU",
    alpha3: "MUS",
    numeric: "480",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      "en-MU",
      "fr-MU",
      // Mauritian Creole (mfe) - no 639-1
    ],
  },
  {
    name: "Mayotte",
    alpha2: "YT",
    alpha3: "MYT",
    numeric: "175",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-YT"],
  },
  {
    name: "Mexico",
    alpha2: "MX",
    alpha3: "MEX",
    numeric: "484",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["es-MX"],
  },
  {
    name: "Micronesia (Federated States of)",
    alpha2: "FM",
    alpha3: "FSM",
    numeric: "583",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["en-FM"],
  },
  {
    name: "Republic of Moldova",
    alpha2: "MD",
    alpha3: "MDA",
    numeric: "498",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["ro-MD", "ru-MD"],
  },
  {
    name: "Monaco",
    alpha2: "MC",
    alpha3: "MCO",
    numeric: "492",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["fr-MC"],
  },
  {
    name: "Mongolia",
    alpha2: "MN",
    alpha3: "MNG",
    numeric: "496",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["mn-MN"],
  },
  {
    name: "Montenegro",
    alpha2: "ME",
    alpha3: "MNE",
    numeric: "499",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["sr-ME"],
  },
  {
    name: "Montserrat",
    alpha2: "MS",
    alpha3: "MSR",
    numeric: "500",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-MS"],
  },
  {
    name: "Morocco",
    alpha2: "MA",
    alpha3: "MAR",
    numeric: "504",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-MA", "ber-MA"],
  },
  {
    name: "Mozambique",
    alpha2: "MZ",
    alpha3: "MOZ",
    numeric: "508",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["pt-MZ"],
  },
  {
    name: "Myanmar",
    alpha2: "MM",
    alpha3: "MMR",
    numeric: "104",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["my-MM"],
  },
  {
    name: "Namibia",
    alpha2: "NA",
    alpha3: "NAM",
    numeric: "516",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-NA"],
  },
  {
    name: "Nauru",
    alpha2: "NR",
    alpha3: "NRU",
    numeric: "520",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["na-NR", "en-NR"],
  },
  {
    name: "Nepal",
    alpha2: "NP",
    alpha3: "NPL",
    numeric: "524",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["ne-NP"],
  },
  {
    name: "Netherlands",
    alpha2: "NL",
    alpha3: "NLD",
    numeric: "528",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["nl-NL"],
  },
  {
    name: "New Caledonia",
    alpha2: "NC",
    alpha3: "NCL",
    numeric: "540",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["fr-NC"],
  },
  {
    name: "New Zealand",
    alpha2: "NZ",
    alpha3: "NZL",
    numeric: "554",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["en-NZ", "mi-NZ", "nzs-NZ"],
  },
  {
    name: "Nicaragua",
    alpha2: "NI",
    alpha3: "NIC",
    numeric: "558",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["es-NI"],
  },
  {
    name: "Niger",
    alpha2: "NE",
    alpha3: "NER",
    numeric: "562",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-NE"],
  },
  {
    name: "Nigeria",
    alpha2: "NG",
    alpha3: "NGA",
    numeric: "566",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      "en-NG",
      // Major regional languages like Hausa, Yoruba, Igbo also spoken.
    ],
  },
  {
    name: "Niue",
    alpha2: "NU",
    alpha3: "NIU",
    numeric: "570",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["niu-NU", "en-NU"],
  },
  {
    name: "Norfolk Island",
    alpha2: "NF",
    alpha3: "NFK",
    numeric: "574",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      "en-NF",
      // Norfuk (nfk) - no 639-1
    ],
  },
  {
    name: "Republic of North Macedonia",
    alpha2: "MK",
    alpha3: "MKD",
    numeric: "807",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["mk-MK"],
  },
  {
    name: "Northern Mariana Islands",
    alpha2: "MP",
    alpha3: "MNP",
    numeric: "580",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["en-MP", "ch-MP"],
  },
  {
    name: "Norway",
    alpha2: "NO",
    alpha3: "NOR",
    numeric: "578",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      "nb-NO",
      "nn-NO",
      // Sami languages also recognized.
    ],
  },
  {
    name: "Oman",
    alpha2: "OM",
    alpha3: "OMN",
    numeric: "512",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-OM"],
  },
  {
    name: "Pakistan",
    alpha2: "PK",
    alpha3: "PAK",
    numeric: "586",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["ur-PK", "en-PK"],
  },
  {
    name: "Palau",
    alpha2: "PW",
    alpha3: "PLW",
    numeric: "585",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["pau-PW", "en-PW"],
  },
  {
    name: "Palestine, State of",
    alpha2: "PS",
    alpha3: "PSE",
    numeric: "275",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-PS"],
  },
  {
    name: "Panama",
    alpha2: "PA",
    alpha3: "PAN",
    numeric: "591",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["es-PA"],
  },
  {
    name: "Papua New Guinea",
    alpha2: "PG",
    alpha3: "PNG",
    numeric: "598",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      "tpi-PG",
      "ho-PG",
      "en-PG",
      // Over 800 indigenous languages
    ],
  },
  {
    name: "Paraguay",
    alpha2: "PY",
    alpha3: "PRY",
    numeric: "600",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["es-PY", "gn-PY"],
  },
  {
    name: "Peru",
    alpha2: "PE",
    alpha3: "PER",
    numeric: "604",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["es-PE", "qu-PE"],
  },
  {
    name: "Philippines",
    alpha2: "PH",
    alpha3: "PHL",
    numeric: "608",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["fil-PH", "en-PH"],
  },
  {
    name: "Pitcairn",
    alpha2: "PN",
    alpha3: "PCN",
    numeric: "612",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      "en-PN",
      // Pitkern (pih) - no 639-1
    ],
  },
  {
    name: "Poland",
    alpha2: "PL",
    alpha3: "POL",
    numeric: "616",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["pl-PL"],
  },
  {
    name: "Portugal",
    alpha2: "PT",
    alpha3: "PRT",
    numeric: "620",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["pt-PT"],
  },
  {
    name: "Puerto Rico",
    alpha2: "PR",
    alpha3: "PRI",
    numeric: "630",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["es-PR", "en-PR"],
  },
  {
    name: "Qatar",
    alpha2: "QA",
    alpha3: "QAT",
    numeric: "634",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-QA"],
  },
  {
    name: "Réunion",
    alpha2: "RE",
    alpha3: "REU",
    numeric: "638",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-RE"],
  },
  {
    name: "Romania",
    alpha2: "RO",
    alpha3: "ROU",
    numeric: "642",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["ro-RO"],
  },
  {
    name: "Russian Federation",
    alpha2: "RU",
    alpha3: "RUS",
    numeric: "643",
    continents: ["Europe", "Asia"],
    regions: ["EMEA", "APAC"],
    dialects: ["ru-RU"],
  },
  {
    name: "Rwanda",
    alpha2: "RW",
    alpha3: "RWA",
    numeric: "646",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["rw-RW", "en-RW"],
  },
  {
    name: "Saint Barthélemy",
    alpha2: "BL",
    alpha3: "BLM",
    numeric: "652",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["fr-BL"],
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2: "SH",
    alpha3: "SHN",
    numeric: "654",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-SH"],
  },
  {
    name: "Saint Kitts and Nevis",
    alpha2: "KN",
    alpha3: "KNA",
    numeric: "659",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-KN"],
  },
  {
    name: "Saint Lucia",
    alpha2: "LC",
    alpha3: "LCA",
    numeric: "662",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-LC"],
  },
  {
    name: "Saint Martin (French part)",
    alpha2: "MF",
    alpha3: "MAF",
    numeric: "663",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["fr-MF"],
  },
  {
    name: "Saint Pierre and Miquelon",
    alpha2: "PM",
    alpha3: "SPM",
    numeric: "666",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: ["fr-PM"],
  },
  {
    name: "Saint Vincent and the Grenadines",
    alpha2: "VC",
    alpha3: "VCT",
    numeric: "670",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-VC"],
  },
  {
    name: "Samoa",
    alpha2: "WS",
    alpha3: "WSM",
    numeric: "882",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["sm-WS", "en-WS"],
  },
  {
    name: "San Marino",
    alpha2: "SM",
    alpha3: "SMR",
    numeric: "674",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["it-SM"],
  },
  {
    name: "Sao Tome and Principe",
    alpha2: "ST",
    alpha3: "STP",
    numeric: "678",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["pt-ST"],
  },
  {
    name: "Saudi Arabia",
    alpha2: "SA",
    alpha3: "SAU",
    numeric: "682",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-SA"],
  },
  {
    name: "Senegal",
    alpha2: "SN",
    alpha3: "SEN",
    numeric: "686",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-SN"],
  },
  {
    name: "Serbia",
    alpha2: "RS",
    alpha3: "SRB",
    numeric: "688",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["sr-RS"],
  },
  {
    name: "Seychelles",
    alpha2: "SC",
    alpha3: "SYC",
    numeric: "690",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["crs-SC", "en-SC", "fr-SC"],
  },
  {
    name: "Sierra Leone",
    alpha2: "SL",
    alpha3: "SLE",
    numeric: "694",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      "en-SL",
      // Krio (kri) - no 639-1
    ],
  },
  {
    name: "Singapore",
    alpha2: "SG",
    alpha3: "SGP",
    numeric: "702",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["en-SG", "ms-SG", "zh-Hans-SG", "ta-SG"],
  },
  {
    name: "Sint Maarten (Dutch part)",
    alpha2: "SX",
    alpha3: "SXM",
    numeric: "534",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["nl-SX", "en-SX"],
  },
  {
    name: "Slovakia",
    alpha2: "SK",
    alpha3: "SVK",
    numeric: "703",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["sk-SK"],
  },
  {
    name: "Slovenia",
    alpha2: "SI",
    alpha3: "SVN",
    numeric: "705",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["sl-SI"],
  },
  {
    name: "Solomon Islands",
    alpha2: "SB",
    alpha3: "SLB",
    numeric: "090",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      "en-SB",
      // Pijin (pis) - no 639-1
    ],
  },
  {
    name: "Somalia",
    alpha2: "SO",
    alpha3: "SOM",
    numeric: "706",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["so-SO", "ar-SO"],
  },
  {
    name: "South Africa",
    alpha2: "ZA",
    alpha3: "ZAF",
    numeric: "710",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: [
      "af-ZA",
      "en-ZA",
      "zu-ZA",
      "xh-ZA",
      "st-ZA",
      "tn-ZA",
      "ss-ZA",
      "ve-ZA",
      "ts-ZA",
      "nso-ZA",
      "nr-ZA",
    ],
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    alpha2: "GS",
    alpha3: "SGS",
    numeric: "239",
    continents: ["Antarctica"],
    regions: [],
    dialects: ["en-GS"],
  },
  {
    name: "South Sudan",
    alpha2: "SS",
    alpha3: "SSD",
    numeric: "728",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-SS"],
  },
  {
    name: "Spain",
    alpha2: "ES",
    alpha3: "ESP",
    numeric: "724",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: [
      "es-ES",
      "ca-ES",
      "gl-ES",
      "eu-ES",
      // Aranese, Valencian, etc. are also recognized in specific regions
    ],
  },
  {
    name: "Sri Lanka",
    alpha2: "LK",
    alpha3: "LKA",
    numeric: "144",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["si-LK", "ta-LK"],
  },
  {
    name: "Sudan",
    alpha2: "SD",
    alpha3: "SDN",
    numeric: "729",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-SD", "en-SD"],
  },
  {
    name: "Suriname",
    alpha2: "SR",
    alpha3: "SUR",
    numeric: "740",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["nl-SR"],
  },
  {
    name: "Svalbard and Jan Mayen",
    alpha2: "SJ",
    alpha3: "SJM",
    numeric: "744",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["no-SJ"],
  },
  {
    name: "Sweden",
    alpha2: "SE",
    alpha3: "SWE",
    numeric: "752",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["sv-SE"],
  },
  {
    name: "Switzerland",
    alpha2: "CH",
    alpha3: "CHE",
    numeric: "756",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["de-CH", "fr-CH", "it-CH", "rm-CH"],
  },
  {
    name: "Syrian Arab Republic",
    alpha2: "SY",
    alpha3: "SYR",
    numeric: "760",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-SY"],
  },
  {
    name: "Taiwan (Province of China)",
    alpha2: "TW",
    alpha3: "TWN",
    numeric: "158",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["zh-Hant-TW"],
  },
  {
    name: "Tajikistan",
    alpha2: "TJ",
    alpha3: "TJK",
    numeric: "762",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["tg-TJ", "ru-TJ"],
  },
  {
    name: "Tanzania, United Republic of",
    alpha2: "TZ",
    alpha3: "TZA",
    numeric: "834",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["sw-TZ", "en-TZ"],
  },
  {
    name: "Thailand",
    alpha2: "TH",
    alpha3: "THA",
    numeric: "764",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["th-TH"],
  },
  {
    name: "Timor-Leste",
    alpha2: "TL",
    alpha3: "TLS",
    numeric: "626",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["tet-TL", "pt-TL"],
  },
  {
    name: "Togo",
    alpha2: "TG",
    alpha3: "TGO",
    numeric: "768",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["fr-TG"],
  },
  {
    name: "Tokelau",
    alpha2: "TK",
    alpha3: "TKL",
    numeric: "772",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["tkl-TK", "en-TK"],
  },
  {
    name: "Tonga",
    alpha2: "TO",
    alpha3: "TON",
    numeric: "776",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["to-TO", "en-TO"],
  },
  {
    name: "Trinidad and Tobago",
    alpha2: "TT",
    alpha3: "TTO",
    numeric: "780",
    continents: ["South America", "Africa"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["en-TT"],
  },
  {
    name: "Tunisia",
    alpha2: "TN",
    alpha3: "TUN",
    numeric: "788",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-TN"],
  },
  {
    name: "Turkey",
    alpha2: "TR",
    alpha3: "TUR",
    numeric: "792",
    continents: ["Asia", "Europe"],
    regions: ["EMEA"],
    dialects: ["tr-TR"],
  },
  {
    name: "Turkmenistan",
    alpha2: "TM",
    alpha3: "TKM",
    numeric: "795",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["tk-TM", "ru-TM"],
  },
  {
    name: "Turks and Caicos Islands",
    alpha2: "TC",
    alpha3: "TCA",
    numeric: "796",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-TC"],
  },
  {
    name: "Tuvalu",
    alpha2: "TV",
    alpha3: "TUV",
    numeric: "798",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["tvl-TV", "en-TV"],
  },
  {
    name: "Uganda",
    alpha2: "UG",
    alpha3: "UGA",
    numeric: "800",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-UG", "lg-UG", "sw-UG"],
  },
  {
    name: "Ukraine",
    alpha2: "UA",
    alpha3: "UKR",
    numeric: "804",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["uk-UA"],
  },
  {
    name: "United Arab Emirates",
    alpha2: "AE",
    alpha3: "ARE",
    numeric: "784",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-AE"],
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    alpha2: "GB",
    alpha3: "GBR",
    numeric: "826",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["en-GB", "gd-GB", "cy-GB", "ga-GB", "kw-GB", "sco-GB"],
  },
  {
    name: "United States Minor Outlying Islands",
    alpha2: "UM",
    alpha3: "UMI",
    numeric: "581",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["en-UM"],
  },
  {
    name: "United States of America",
    alpha2: "US",
    alpha3: "USA",
    numeric: "840",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: ["en-US"],
  },
  {
    name: "Uruguay",
    alpha2: "UY",
    alpha3: "URY",
    numeric: "858",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["es-UY"],
  },
  {
    name: "Uzbekistan",
    alpha2: "UZ",
    alpha3: "UZB",
    numeric: "860",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["uz-UZ", "ru-UZ"],
  },
  {
    name: "Vanuatu",
    alpha2: "VU",
    alpha3: "VUT",
    numeric: "548",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: ["bi-VU", "en-VU", "fr-VU"],
  },
  {
    name: "Bolivarian Republic of Venezuela",
    alpha2: "VE",
    alpha3: "VEN",
    numeric: "862",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
    dialects: ["es-VE"],
  },
  {
    name: "Vietnam",
    alpha2: "VN",
    alpha3: "VNM",
    numeric: "704",
    continents: ["Asia"],
    regions: ["APAC"],
    dialects: ["vi-VN"],
  },
  {
    name: "Virgin Islands (British)",
    alpha2: "VG",
    alpha3: "VGB",
    numeric: "092",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
    dialects: ["en-VG"],
  },
  {
    name: "Virgin Islands (U.S.)",
    alpha2: "VI",
    alpha3: "VIR",
    numeric: "850",
    continents: ["North America"],
    regions: ["AMER", "NA"],
    dialects: ["en-VI"],
  },
  {
    name: "Wallis and Futuna",
    alpha2: "WF",
    alpha3: "WLF",
    numeric: "876",
    continents: ["Oceania"],
    regions: ["APAC"],
    dialects: [
      "fr-WF",
      // Wallisian (wls) and Futunan (fud) - no 639-1
    ],
  },
  {
    name: "Western Sahara",
    alpha2: "EH",
    alpha3: "ESH",
    numeric: "732",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-EH", "es-EH"],
  },
  {
    name: "Yemen",
    alpha2: "YE",
    alpha3: "YEM",
    numeric: "887",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
    dialects: ["ar-YE"],
  },
  {
    name: "Zambia",
    alpha2: "ZM",
    alpha3: "ZMB",
    numeric: "894",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-ZM"],
  },
  {
    name: "Zimbabwe",
    alpha2: "ZW",
    alpha3: "ZWE",
    numeric: "716",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
    dialects: ["en-ZW", "sn-ZW", "nd-ZW"],
  },
  {
    name: "Åland Islands",
    alpha2: "AX",
    alpha3: "ALA",
    numeric: "248",
    continents: ["Europe"],
    regions: ["EMEA"],
    dialects: ["sv-AX"],
  },
];

export const continents: Array<Continent> = [
  "Africa",
  "Antarctica",
  "Asia",
  "Europe",
  "North America",
  "Oceania",
  "South America",
];

export const regions: Array<Region> = [
  "EMEA",
  "APAC",
  "AMER",
  "LATAM",
  "NA",
  "SA",
  "MEA",
];
