import type { Continent } from "./continent";
import type { ISO3166 } from "./iso-3166";
import { z } from "zod";
import type { Region } from "./region";

export const countries: Array<ISO3166> = [
  {
    name: "Afghanistan",
    alpha2: "AF",
    alpha3: "AFG",
    numeric: "004",
    continents: ["Asia"],
    regions: ["APAC", "MEA"],
  },
  {
    name: "Albania",
    alpha2: "AL",
    alpha3: "ALB",
    numeric: "008",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Algeria",
    alpha2: "DZ",
    alpha3: "DZA",
    numeric: "012",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "American Samoa",
    alpha2: "AS",
    alpha3: "ASM",
    numeric: "016",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Andorra",
    alpha2: "AD",
    alpha3: "AND",
    numeric: "020",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Angola",
    alpha2: "AO",
    alpha3: "AGO",
    numeric: "024",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Anguilla",
    alpha2: "AI",
    alpha3: "AIA",
    numeric: "660",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Antarctica",
    alpha2: "AQ",
    alpha3: "ATA",
    numeric: "010",
    continents: ["Antarctica"],
    regions: [],
  },
  {
    name: "Antigua and Barbuda",
    alpha2: "AG",
    alpha3: "ATG",
    numeric: "028",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Argentina",
    alpha2: "AR",
    alpha3: "ARG",
    numeric: "032",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Armenia",
    alpha2: "AM",
    alpha3: "ARM",
    numeric: "051",
    continents: ["Asia", "Europe"], // Geographically Asia, but often included in Europe/EMEA for business.
    regions: ["EMEA", "APAC"],
  },
  {
    name: "Aruba",
    alpha2: "AW",
    alpha3: "ABW",
    numeric: "533",
    continents: ["South America", "Europe"], // Geographically South America, politically part of Netherlands (Europe)
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Australia",
    alpha2: "AU",
    alpha3: "AUS",
    numeric: "036",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Austria",
    alpha2: "AT",
    alpha3: "AUT",
    numeric: "040",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Azerbaijan",
    alpha2: "AZ",
    alpha3: "AZE",
    numeric: "031",
    continents: ["Asia", "Europe"], // Geographically Asia, but often included in Europe/EMEA for business.
    regions: ["EMEA", "APAC"],
  },
  {
    name: "Bahamas",
    alpha2: "BS",
    alpha3: "BHS",
    numeric: "044",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Bahrain",
    alpha2: "BH",
    alpha3: "BHR",
    numeric: "048",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Bangladesh",
    alpha2: "BD",
    alpha3: "BGD",
    numeric: "050",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Barbados",
    alpha2: "BB",
    alpha3: "BRB",
    numeric: "052",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Belarus",
    alpha2: "BY",
    alpha3: "BLR",
    numeric: "112",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Belgium",
    alpha2: "BE",
    alpha3: "BEL",
    numeric: "056",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Belize",
    alpha2: "BZ",
    alpha3: "BLZ",
    numeric: "084",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Benin",
    alpha2: "BJ",
    alpha3: "BEN",
    numeric: "204",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Bermuda",
    alpha2: "BM",
    alpha3: "BMU",
    numeric: "060",
    continents: ["North America"],
    regions: ["AMER", "NA"],
  },
  {
    name: "Bhutan",
    alpha2: "BT",
    alpha3: "BTN",
    numeric: "064",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Plurinational State of Bolivia",
    alpha2: "BO",
    alpha3: "BOL",
    numeric: "068",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    alpha2: "BQ",
    alpha3: "BES",
    numeric: "535",
    continents: ["South America", "Europe"], // Geographically South America, politically part of Netherlands (Europe)
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Bosnia and Herzegovina",
    alpha2: "BA",
    alpha3: "BIH",
    numeric: "070",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Botswana",
    alpha2: "BW",
    alpha3: "BWA",
    numeric: "072",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Bouvet Island",
    alpha2: "BV",
    alpha3: "BVT",
    numeric: "074",
    continents: ["Antarctica"],
    regions: [],
  },
  {
    name: "Brazil",
    alpha2: "BR",
    alpha3: "BRA",
    numeric: "076",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "British Indian Ocean Territory",
    alpha2: "IO",
    alpha3: "IOT",
    numeric: "086",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Brunei Darussalam",
    alpha2: "BN",
    alpha3: "BRN",
    numeric: "096",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Bulgaria",
    alpha2: "BG",
    alpha3: "BGR",
    numeric: "100",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Burkina Faso",
    alpha2: "BF",
    alpha3: "BFA",
    numeric: "854",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Burundi",
    alpha2: "BI",
    alpha3: "BDI",
    numeric: "108",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Cape Verde",
    alpha2: "CV",
    alpha3: "CPV",
    numeric: "132",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Cambodia",
    alpha2: "KH",
    alpha3: "KHM",
    numeric: "116",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Cameroon",
    alpha2: "CM",
    alpha3: "CMR",
    numeric: "120",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Canada",
    alpha2: "CA",
    alpha3: "CAN",
    numeric: "124",
    continents: ["North America"],
    regions: ["AMER", "NA"],
  },
  {
    name: "Cayman Islands",
    alpha2: "KY",
    alpha3: "CYM",
    numeric: "136",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Central African Republic",
    alpha2: "CF",
    alpha3: "CAF",
    numeric: "140",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Chad",
    alpha2: "TD",
    alpha3: "TCD",
    numeric: "148",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Chile",
    alpha2: "CL",
    alpha3: "CHL",
    numeric: "152",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "China",
    alpha2: "CN",
    alpha3: "CHN",
    numeric: "156",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Christmas Island",
    alpha2: "CX",
    alpha3: "CXR",
    numeric: "162",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Cocos (Keeling) Islands",
    alpha2: "CC",
    alpha3: "CCK",
    numeric: "166",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Colombia",
    alpha2: "CO",
    alpha3: "COL",
    numeric: "170",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Comoros",
    alpha2: "KM",
    alpha3: "COM",
    numeric: "174",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Congo",
    alpha2: "CG",
    alpha3: "COG",
    numeric: "178",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Democratic Republic of Congo",
    alpha2: "CD",
    alpha3: "COD",
    numeric: "180",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Cook Islands",
    alpha2: "CK",
    alpha3: "COK",
    numeric: "184",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Costa Rica",
    alpha2: "CR",
    alpha3: "CRI",
    numeric: "188",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Côte d'Ivoire",
    alpha2: "CI",
    alpha3: "CIV",
    numeric: "384",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Croatia",
    alpha2: "HR",
    alpha3: "HRV",
    numeric: "191",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Cuba",
    alpha2: "CU",
    alpha3: "CUB",
    numeric: "192",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Curaçao",
    alpha2: "CW",
    alpha3: "CUW",
    numeric: "531",
    continents: ["South America", "Europe"], // Geographically South America, politically part of Netherlands (Europe)
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Cyprus",
    alpha2: "CY",
    alpha3: "CYP",
    numeric: "196",
    continents: ["Europe", "Asia"], // Geographically Asia, but culturally and politically European
    regions: ["EMEA"],
  },
  {
    name: "Czechia", // Updated name from "Czech Republic"
    alpha2: "CZ",
    alpha3: "CZE",
    numeric: "203",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Denmark",
    alpha2: "DK",
    alpha3: "DNK",
    numeric: "208",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Djibouti",
    alpha2: "DJ",
    alpha3: "DJI",
    numeric: "262",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Dominica",
    alpha2: "DM",
    alpha3: "DMA",
    numeric: "212",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Dominican Republic",
    alpha2: "DO",
    alpha3: "DOM",
    numeric: "214",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Ecuador",
    alpha2: "EC",
    alpha3: "ECU",
    numeric: "218",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Egypt",
    alpha2: "EG",
    alpha3: "EGY",
    numeric: "818",
    continents: ["Africa", "Asia"], // Part of Africa and Asia (Sinai Peninsula)
    regions: ["EMEA", "MEA"],
  },
  {
    name: "El Salvador",
    alpha2: "SV",
    alpha3: "SLV",
    numeric: "222",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Equatorial Guinea",
    alpha2: "GQ",
    alpha3: "GNQ",
    numeric: "226",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Eritrea",
    alpha2: "ER",
    alpha3: "ERI",
    numeric: "232",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Estonia",
    alpha2: "EE",
    alpha3: "EST",
    numeric: "233",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Eswatini", // Updated name from "Swaziland"
    alpha2: "SZ",
    alpha3: "SWZ",
    numeric: "748",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Ethiopia",
    alpha2: "ET",
    alpha3: "ETH",
    numeric: "231",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Falkland Islands",
    alpha2: "FK",
    alpha3: "FLK",
    numeric: "238",
    continents: ["South America"],
    regions: ["AMER", "SA"],
  },
  {
    name: "Faroe Islands",
    alpha2: "FO",
    alpha3: "FRO",
    numeric: "234",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Fiji",
    alpha2: "FJ",
    alpha3: "FJI",
    numeric: "242",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Finland",
    alpha2: "FI",
    alpha3: "FIN",
    numeric: "246",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "France",
    alpha2: "FR",
    alpha3: "FRA",
    numeric: "250",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "French Guiana",
    alpha2: "GF",
    alpha3: "GUF",
    numeric: "254",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "French Polynesia",
    alpha2: "PF",
    alpha3: "PYF",
    numeric: "258",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "French Southern Territories",
    alpha2: "TF",
    alpha3: "ATF",
    numeric: "260",
    continents: ["Antarctica"], // Also in Indian Ocean
    regions: [],
  },
  {
    name: "Gabon",
    alpha2: "GA",
    alpha3: "GAB",
    numeric: "266",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Gambia",
    alpha2: "GM",
    alpha3: "GMB",
    numeric: "270",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Georgia",
    alpha2: "GE",
    alpha3: "GEO",
    numeric: "268",
    continents: ["Asia", "Europe"], // Geographically Asia, but culturally and politically often European/EMEA
    regions: ["EMEA"],
  },
  {
    name: "Germany",
    alpha2: "DE",
    alpha3: "DEU",
    numeric: "276",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Ghana",
    alpha2: "GH",
    alpha3: "GHA",
    numeric: "288",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Gibraltar",
    alpha2: "GI",
    alpha3: "GIB",
    numeric: "292",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Greece",
    alpha2: "GR",
    alpha3: "GRC",
    numeric: "300",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Greenland",
    alpha2: "GL",
    alpha3: "GRL",
    numeric: "304",
    continents: ["North America"],
    regions: ["AMER", "NA"],
  },
  {
    name: "Grenada",
    alpha2: "GD",
    alpha3: "GRD",
    numeric: "308",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Guadeloupe",
    alpha2: "GP",
    alpha3: "GLP",
    numeric: "312",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Guam",
    alpha2: "GU",
    alpha3: "GUM",
    numeric: "316",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Guatemala",
    alpha2: "GT",
    alpha3: "GTM",
    numeric: "320",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Guernsey",
    alpha2: "GG",
    alpha3: "GGY",
    numeric: "831",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Guinea",
    alpha2: "GN",
    alpha3: "GIN",
    numeric: "324",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Guinea-Bissau",
    alpha2: "GW",
    alpha3: "GNB",
    numeric: "624",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Guyana",
    alpha2: "GY",
    alpha3: "GUY",
    numeric: "328",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Haiti",
    alpha2: "HT",
    alpha3: "HTI",
    numeric: "332",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Heard Island and McDonald Islands",
    alpha2: "HM",
    alpha3: "HMD",
    numeric: "334",
    continents: ["Antarctica"],
    regions: [],
  },
  {
    name: "Holy See",
    alpha2: "VA",
    alpha3: "VAT",
    numeric: "336",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Honduras",
    alpha2: "HN",
    alpha3: "HND",
    numeric: "340",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Hong Kong",
    alpha2: "HK",
    alpha3: "HKG",
    numeric: "344",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Hungary",
    alpha2: "HU",
    alpha3: "HUN",
    numeric: "348",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Iceland",
    alpha2: "IS",
    alpha3: "ISL",
    numeric: "352",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "India",
    alpha2: "IN",
    alpha3: "IND",
    numeric: "356",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Indonesia",
    alpha2: "ID",
    alpha3: "IDN",
    numeric: "360",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Iran (Islamic Republic of)",
    alpha2: "IR",
    alpha3: "IRN",
    numeric: "364",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Iraq",
    alpha2: "IQ",
    alpha3: "IRQ",
    numeric: "368",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Ireland",
    alpha2: "IE",
    alpha3: "IRL",
    numeric: "372",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Isle of Man",
    alpha2: "IM",
    alpha3: "IMN",
    numeric: "833",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Israel",
    alpha2: "IL",
    alpha3: "ISR",
    numeric: "376",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Italy",
    alpha2: "IT",
    alpha3: "ITA",
    numeric: "380",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Jamaica",
    alpha2: "JM",
    alpha3: "JAM",
    numeric: "388",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Japan",
    alpha2: "JP",
    alpha3: "JPN",
    numeric: "392",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Jersey",
    alpha2: "JE",
    alpha3: "JEY",
    numeric: "832",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Jordan",
    alpha2: "JO",
    alpha3: "JOR",
    numeric: "400",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Kazakhstan",
    alpha2: "KZ",
    alpha3: "KAZ",
    numeric: "398",
    continents: ["Asia", "Europe"], // Partially Europe
    regions: ["EMEA", "APAC"],
  },
  {
    name: "Kenya",
    alpha2: "KE",
    alpha3: "KEN",
    numeric: "404",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Kiribati",
    alpha2: "KI",
    alpha3: "KIR",
    numeric: "296",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Democratic People's Republic of Korea",
    alpha2: "KP",
    alpha3: "PRK",
    numeric: "408",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Republic of Korea",
    alpha2: "KR",
    alpha3: "KOR",
    numeric: "410",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Kuwait",
    alpha2: "KW",
    alpha3: "KWT",
    numeric: "414",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Kyrgyzstan",
    alpha2: "KG",
    alpha3: "KGZ",
    numeric: "417",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2: "LA",
    alpha3: "LAO",
    numeric: "418",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Latvia",
    alpha2: "LV",
    alpha3: "LVA",
    numeric: "428",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Lebanon",
    alpha2: "LB",
    alpha3: "LBN",
    numeric: "422",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Lesotho",
    alpha2: "LS",
    alpha3: "LSO",
    numeric: "426",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Liberia",
    alpha2: "LR",
    alpha3: "LBR",
    numeric: "430",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Libya",
    alpha2: "LY",
    alpha3: "LBY",
    numeric: "434",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Liechtenstein",
    alpha2: "LI",
    alpha3: "LIE",
    numeric: "438",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Lithuania",
    alpha2: "LT",
    alpha3: "LTU",
    numeric: "440",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Luxembourg",
    alpha2: "LU",
    alpha3: "LUX",
    numeric: "442",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Macao",
    alpha2: "MO",
    alpha3: "MAC",
    numeric: "446",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Madagascar",
    alpha2: "MG",
    alpha3: "MDG",
    numeric: "450",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Malawi",
    alpha2: "MW",
    alpha3: "MWI",
    numeric: "454",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Malaysia",
    alpha2: "MY",
    alpha3: "MYS",
    numeric: "458",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Maldives",
    alpha2: "MV",
    alpha3: "MDV",
    numeric: "462",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Mali",
    alpha2: "ML",
    alpha3: "MLI",
    numeric: "466",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Malta",
    alpha2: "MT",
    alpha3: "MLT",
    numeric: "470",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Marshall Islands",
    alpha2: "MH",
    alpha3: "MHL",
    numeric: "584",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Martinique",
    alpha2: "MQ",
    alpha3: "MTQ",
    numeric: "474",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Mauritania",
    alpha2: "MR",
    alpha3: "MRT",
    numeric: "478",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Mauritius",
    alpha2: "MU",
    alpha3: "MUS",
    numeric: "480",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Mayotte",
    alpha2: "YT",
    alpha3: "MYT",
    numeric: "175",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Mexico",
    alpha2: "MX",
    alpha3: "MEX",
    numeric: "484",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Micronesia (Federated States of)",
    alpha2: "FM",
    alpha3: "FSM",
    numeric: "583",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Republic of Moldova",
    alpha2: "MD",
    alpha3: "MDA",
    numeric: "498",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Monaco",
    alpha2: "MC",
    alpha3: "MCO",
    numeric: "492",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Mongolia",
    alpha2: "MN",
    alpha3: "MNG",
    numeric: "496",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Montenegro",
    alpha2: "ME",
    alpha3: "MNE",
    numeric: "499",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Montserrat",
    alpha2: "MS",
    alpha3: "MSR",
    numeric: "500",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Morocco",
    alpha2: "MA",
    alpha3: "MAR",
    numeric: "504",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Mozambique",
    alpha2: "MZ",
    alpha3: "MOZ",
    numeric: "508",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Myanmar",
    alpha2: "MM",
    alpha3: "MMR",
    numeric: "104",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Namibia",
    alpha2: "NA",
    alpha3: "NAM",
    numeric: "516",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Nauru",
    alpha2: "NR",
    alpha3: "NRU",
    numeric: "520",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Nepal",
    alpha2: "NP",
    alpha3: "NPL",
    numeric: "524",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Netherlands",
    alpha2: "NL",
    alpha3: "NLD",
    numeric: "528",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "New Caledonia",
    alpha2: "NC",
    alpha3: "NCL",
    numeric: "540",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "New Zealand",
    alpha2: "NZ",
    alpha3: "NZL",
    numeric: "554",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Nicaragua",
    alpha2: "NI",
    alpha3: "NIC",
    numeric: "558",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Niger",
    alpha2: "NE",
    alpha3: "NER",
    numeric: "562",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Nigeria",
    alpha2: "NG",
    alpha3: "NGA",
    numeric: "566",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Niue",
    alpha2: "NU",
    alpha3: "NIU",
    numeric: "570",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Norfolk Island",
    alpha2: "NF",
    alpha3: "NFK",
    numeric: "574",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Republic of North Macedonia",
    alpha2: "MK",
    alpha3: "MKD",
    numeric: "807",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Northern Mariana Islands",
    alpha2: "MP",
    alpha3: "MNP",
    numeric: "580",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Norway",
    alpha2: "NO",
    alpha3: "NOR",
    numeric: "578",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Oman",
    alpha2: "OM",
    alpha3: "OMN",
    numeric: "512",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Pakistan",
    alpha2: "PK",
    alpha3: "PAK",
    numeric: "586",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Palau",
    alpha2: "PW",
    alpha3: "PLW",
    numeric: "585",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Palestine, State of",
    alpha2: "PS",
    alpha3: "PSE",
    numeric: "275",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Panama",
    alpha2: "PA",
    alpha3: "PAN",
    numeric: "591",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Papua New Guinea",
    alpha2: "PG",
    alpha3: "PNG",
    numeric: "598",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Paraguay",
    alpha2: "PY",
    alpha3: "PRY",
    numeric: "600",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Peru",
    alpha2: "PE",
    alpha3: "PER",
    numeric: "604",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Philippines",
    alpha2: "PH",
    alpha3: "PHL",
    numeric: "608",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Pitcairn",
    alpha2: "PN",
    alpha3: "PCN",
    numeric: "612",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Poland",
    alpha2: "PL",
    alpha3: "POL",
    numeric: "616",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Portugal",
    alpha2: "PT",
    alpha3: "PRT",
    numeric: "620",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Puerto Rico",
    alpha2: "PR",
    alpha3: "PRI",
    numeric: "630",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Qatar",
    alpha2: "QA",
    alpha3: "QAT",
    numeric: "634",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Réunion",
    alpha2: "RE",
    alpha3: "REU",
    numeric: "638",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Romania",
    alpha2: "RO",
    alpha3: "ROU",
    numeric: "642",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Russian Federation",
    alpha2: "RU",
    alpha3: "RUS",
    numeric: "643",
    continents: ["Europe", "Asia"], // Partially Asia
    regions: ["EMEA", "APAC"],
  },
  {
    name: "Rwanda",
    alpha2: "RW",
    alpha3: "RWA",
    numeric: "646",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Saint Barthélemy",
    alpha2: "BL",
    alpha3: "BLM",
    numeric: "652",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2: "SH",
    alpha3: "SHN",
    numeric: "654",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Saint Kitts and Nevis",
    alpha2: "KN",
    alpha3: "KNA",
    numeric: "659",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Saint Lucia",
    alpha2: "LC",
    alpha3: "LCA",
    numeric: "662",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Saint Martin (French part)",
    alpha2: "MF",
    alpha3: "MAF",
    numeric: "663",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Saint Pierre and Miquelon",
    alpha2: "PM",
    alpha3: "SPM",
    numeric: "666",
    continents: ["North America"],
    regions: ["AMER", "NA"],
  },
  {
    name: "Saint Vincent and the Grenadines",
    alpha2: "VC",
    alpha3: "VCT",
    numeric: "670",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Samoa",
    alpha2: "WS",
    alpha3: "WSM",
    numeric: "882",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "San Marino",
    alpha2: "SM",
    alpha3: "SMR",
    numeric: "674",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Sao Tome and Principe",
    alpha2: "ST",
    alpha3: "STP",
    numeric: "678",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Saudi Arabia",
    alpha2: "SA",
    alpha3: "SAU",
    numeric: "682",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Senegal",
    alpha2: "SN",
    alpha3: "SEN",
    numeric: "686",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Serbia",
    alpha2: "RS",
    alpha3: "SRB",
    numeric: "688",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Seychelles",
    alpha2: "SC",
    alpha3: "SYC",
    numeric: "690",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Sierra Leone",
    alpha2: "SL",
    alpha3: "SLE",
    numeric: "694",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Singapore",
    alpha2: "SG",
    alpha3: "SGP",
    numeric: "702",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Sint Maarten (Dutch part)",
    alpha2: "SX",
    alpha3: "SXM",
    numeric: "534",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Slovakia",
    alpha2: "SK",
    alpha3: "SVK",
    numeric: "703",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Slovenia",
    alpha2: "SI",
    alpha3: "SVN",
    numeric: "705",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Solomon Islands",
    alpha2: "SB",
    alpha3: "SLB",
    numeric: "090",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Somalia",
    alpha2: "SO",
    alpha3: "SOM",
    numeric: "706",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "South Africa",
    alpha2: "ZA",
    alpha3: "ZAF",
    numeric: "710",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    alpha2: "GS",
    alpha3: "SGS",
    numeric: "239",
    continents: ["Antarctica"],
    regions: [],
  },
  {
    name: "South Sudan",
    alpha2: "SS",
    alpha3: "SSD",
    numeric: "728",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Spain",
    alpha2: "ES",
    alpha3: "ESP",
    numeric: "724",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Sri Lanka",
    alpha2: "LK",
    alpha3: "LKA",
    numeric: "144",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Sudan",
    alpha2: "SD",
    alpha3: "SDN",
    numeric: "729",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Suriname",
    alpha2: "SR",
    alpha3: "SUR",
    numeric: "740",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Svalbard and Jan Mayen",
    alpha2: "SJ",
    alpha3: "SJM",
    numeric: "744",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Sweden",
    alpha2: "SE",
    alpha3: "SWE",
    numeric: "752",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Switzerland",
    alpha2: "CH",
    alpha3: "CHE",
    numeric: "756",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "Syrian Arab Republic",
    alpha2: "SY",
    alpha3: "SYR",
    numeric: "760",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Taiwan (Province of China)",
    alpha2: "TW",
    alpha3: "TWN",
    numeric: "158",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Tajikistan",
    alpha2: "TJ",
    alpha3: "TJK",
    numeric: "762",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Tanzania, United Republic of",
    alpha2: "TZ",
    alpha3: "TZA",
    numeric: "834",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Thailand",
    alpha2: "TH",
    alpha3: "THA",
    numeric: "764",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Timor-Leste",
    alpha2: "TL",
    alpha3: "TLS",
    numeric: "626",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Togo",
    alpha2: "TG",
    alpha3: "TGO",
    numeric: "768",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Tokelau",
    alpha2: "TK",
    alpha3: "TKL",
    numeric: "772",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Tonga",
    alpha2: "TO",
    alpha3: "TON",
    numeric: "776",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Trinidad and Tobago",
    alpha2: "TT",
    alpha3: "TTO",
    numeric: "780",
    continents: ["South America", "Africa"], // Often grouped with Caribbean/North America due to culture, but geographically SA.
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Tunisia",
    alpha2: "TN",
    alpha3: "TUN",
    numeric: "788",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Turkey",
    alpha2: "TR",
    alpha3: "TUR",
    numeric: "792",
    continents: ["Asia", "Europe"], // Primarily Asia, with a small part in Europe. Often treated as EMEA.
    regions: ["EMEA"],
  },
  {
    name: "Turkmenistan",
    alpha2: "TM",
    alpha3: "TKM",
    numeric: "795",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Turks and Caicos Islands",
    alpha2: "TC",
    alpha3: "TCA",
    numeric: "796",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Tuvalu",
    alpha2: "TV",
    alpha3: "TUV",
    numeric: "798",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Uganda",
    alpha2: "UG",
    alpha3: "UGA",
    numeric: "800",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Ukraine",
    alpha2: "UA",
    alpha3: "UKR",
    numeric: "804",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "United Arab Emirates",
    alpha2: "AE",
    alpha3: "ARE",
    numeric: "784",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    alpha2: "GB",
    alpha3: "GBR",
    numeric: "826",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
  {
    name: "United States Minor Outlying Islands",
    alpha2: "UM",
    alpha3: "UMI",
    numeric: "581",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "United States of America",
    alpha2: "US",
    alpha3: "USA",
    numeric: "840",
    continents: ["North America"],
    regions: ["AMER", "NA"],
  },
  {
    name: "Uruguay",
    alpha2: "UY",
    alpha3: "URY",
    numeric: "858",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Uzbekistan",
    alpha2: "UZ",
    alpha3: "UZB",
    numeric: "860",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Vanuatu",
    alpha2: "VU",
    alpha3: "VUT",
    numeric: "548",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Bolivarian Republic of Venezuela",
    alpha2: "VE",
    alpha3: "VEN",
    numeric: "862",
    continents: ["South America"],
    regions: ["AMER", "LATAM", "SA"],
  },
  {
    name: "Vietnam",
    alpha2: "VN",
    alpha3: "VNM",
    numeric: "704",
    continents: ["Asia"],
    regions: ["APAC"],
  },
  {
    name: "Virgin Islands (British)",
    alpha2: "VG",
    alpha3: "VGB",
    numeric: "092",
    continents: ["North America"],
    regions: ["AMER", "LATAM", "NA"],
  },
  {
    name: "Virgin Islands (U.S.)",
    alpha2: "VI",
    alpha3: "VIR",
    numeric: "850",
    continents: ["North America"],
    regions: ["AMER", "NA"],
  },
  {
    name: "Wallis and Futuna",
    alpha2: "WF",
    alpha3: "WLF",
    numeric: "876",
    continents: ["Oceania"],
    regions: ["APAC"],
  },
  {
    name: "Western Sahara",
    alpha2: "EH",
    alpha3: "ESH",
    numeric: "732",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Yemen",
    alpha2: "YE",
    alpha3: "YEM",
    numeric: "887",
    continents: ["Asia"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Zambia",
    alpha2: "ZM",
    alpha3: "ZMB",
    numeric: "894",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Zimbabwe",
    alpha2: "ZW",
    alpha3: "ZWE",
    numeric: "716",
    continents: ["Africa"],
    regions: ["EMEA", "MEA"],
  },
  {
    name: "Åland Islands",
    alpha2: "AX",
    alpha3: "ALA",
    numeric: "248",
    continents: ["Europe"],
    regions: ["EMEA"],
  },
];

export const continents: Array<Continent> = [
  "Africa",
  "Antarctica",
  "Asia",
  "Europe",
  "North America",
  "Oceania",
  "South America",
];

export const regions: Array<Region> = [
  "EMEA",
  "APAC",
  "AMER",
  "LATAM",
  "NA",
  "SA",
  "MEA",
];
